### ISSUE TITLE
Embedded Font Files Overwriting

### ISSUE THREAD

**Issue by jhornsb2** [plutext/docx4j#147]
I am using version 3.2.1

When calling the processEmbeddings() method in the org.docx4j.openpackaging.parts.WordprocessingML.FontTablePart class the temporary font files that are created overwrite each other.

**Example:**
I make a word document using the Arial font. Some of the Arial text is normal, some bold, some italicized, and some both bold and italicized. I save the file with the embedded fonts option. The method above proceeds to create a temporary Arial.ttf for the regular font. Then it replaces that Arial.ttf file with another Arial.ttf file for bold. That replacement of Arial.ttf repeats for bold italic, and again for italic.

**Update:**
Locally I changed the lines:

```java
getObfuscatedFontFromRelationship(fontName, embedRegular);
getObfuscatedFontFromRelationship(fontName, embedBold);
getObfuscatedFontFromRelationship(fontName, embedBoldItalic);
getObfuscatedFontFromRelationship(fontName, embedItalic);
```

to

```java
getObfuscatedFontFromRelationship(fontName, embedRegular);
getObfuscatedFontFromRelationship(fontName + "Bold", embedBold);
getObfuscatedFontFromRelationship(fontName + "BoldItalic", embedBoldItalic);
getObfuscatedFontFromRelationship(fontName + "Italic", embedItalic);
```

This resulted in the temporary font files Arial.ttf, ArialBold.ttf, ArialBoldItalic.ttf, and ArialItalic.ttf respectively.

Now I processed the embedded fonts, mapped my fonts, and both PhysicalFonts physicalFontMap and my font mapper attached to the instance of WordprocessingMLPackage are displaying the correct font files. But, when I export as a PDF the correct font files are not used. On my windows machine it defaults to the Arial Font located in the fonts folder, but on my Linux server it defaults all bold, bold italicized, and italicized text to the regular version of Arial that was embedded in the word document.

I believe this issue is caused in the org.docx4j.fonts.fop.util.FopConfigUtil class's declareFonts method. In this method, when the different variations of the font are being used it calls the respective PhysicalFonts method. Those methods completely ignore the provided font mapper and the already discovered physical fonts.

**Comment by plutext** [comment]
Fixed by https://github.com/plutext/docx4j/pull/145
