### ISSUE TITLE
xslx4j getting String cell value 

### ISSUE THREAD

**Issue by radiumx3** [plutext/docx4j#166]
As of sample : docx4j/src/samples/xlsx4j/org/xlsx4j/samples/PartsList.java

I'm trying to print my cell's values (Strings) , 

I've seen the usage of deprecated API : getJaxbElement to get the SharedStrings,
- this traversal method that feed a static reference to the sharedStrings object ..

Is there any clean way to do this like an facade getStringValue()  or something less tricky to use ?

**Comment by plutext** [comment]
As of v3.3.3, please see https://github.com/plutext/docx4j/blob/master/src/samples/xlsx4j/org/xlsx4j/samples/CellContentExtractor.java
