### ISSUE TITLE
How to generate the header at the same time and the watermark?

### ISSUE THREAD

**Issue by ngujdi** [plutext/docx4j#171]
######### I refer to the following code example：
https://github.com/plutext/docx4j/blob/master/src/samples/docx4j/org/docx4j/samples/HeaderFooterCreate.java

https://github.com/plutext/docx4j/blob/master/src/samples/docx4j/org/docx4j/samples/Watermark.java

########## The following is the code I wrote：

    private void addHeaderPart(WordprocessingMLPackage wordprocessingMLPackage, MainDocumentPart mainDocumentPart, ObjectFactory objectFactory,
	        Judgement judgement) {
		try {
			Relationship relationship = createTextHeaderPart(mainDocumentPart, objectFactory, judgement.getTitle(), true, "3",
			        JcEnumeration.CENTER);
			createHeaderReference(wordprocessingMLPackage, mainDocumentPart, objectFactory, relationship);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private Relationship createTextHeaderPart(MainDocumentPart mainDocumentPart, ObjectFactory objectFactory, String content, boolean isUnderLine,
	        String underLineSz, JcEnumeration jcEnumeration) throws Exception {
		HeaderPart headerPart = new HeaderPart();
		Relationship relationship = mainDocumentPart.addTargetPart(headerPart);
		headerPart.setJaxbElement(getTextHdr(objectFactory, headerPart, content, isUnderLine, underLineSz, jcEnumeration));
		return relationship;
	}

	private void addWaterMark(WordprocessingMLPackage wordprocessingMLPackage, MainDocumentPart mainDocumentPart, ObjectFactory objectFactory)
	        throws Exception {
		Relationship relationship = createHeaderPart(mainDocumentPart, objectFactory);
		createHeaderReference(wordprocessingMLPackage, mainDocumentPart, objectFactory, relationship);
	}

	private Relationship createHeaderPart(MainDocumentPart mainDocumentPart, ObjectFactory objectFactory) throws Exception {
		HeaderPart headerPart = new HeaderPart();
		Relationship relationship = mainDocumentPart.addTargetPart(headerPart);
		headerPart.setJaxbElement(getHdr(objectFactory));
		return relationship;
	}

	private void createHeaderReference(WordprocessingMLPackage wordprocessingMLPackage, MainDocumentPart mainDocumentPart, ObjectFactory objectFactory,
	        Relationship relationship) {
		List<SectionWrapper> sections = wordprocessingMLPackage.getDocumentModel().getSections();
		SectPr sectPr = sections.get(sections.size() - 1).getSectPr();
		if (sectPr == null) {
			sectPr = objectFactory.createSectPr();
			mainDocumentPart.addObject(sectPr);
			sections.get(sections.size() - 1).setSectPr(sectPr);
		}
		HeaderReference headerReference = objectFactory.createHeaderReference();
		headerReference.setId(relationship.getId());
		headerReference.setType(HdrFtrRef.DEFAULT);
		sectPr.getEGHdrFtrReferences().add(headerReference);
	}

############ Not at the same time generate the header and watermark

**Comment by plutext** [comment]
Should be a forum topic, rather than an issue.
