### ISSUE TITLE
Custom SAXParserFactory without setting system property

### ISSUE THREAD

**Issue by roded** [plutext/docx4j#190]
Hi,
The properties `javax.xml.parsers.SAXParserFactory` and `docx4j.javax.xml.parsers.SAXParserFactory.donotset` currently seem to be mutually exclusive.
Would it be possible to allow setting them both so that the `SAXParserFactory` could be changed for docx4j but not the entire JVM?

**Comment by plutext** [comment]
See comment at https://github.com/plutext/docx4j/blob/master/src/main/java/org/docx4j/XmlUtils.java#L170

The issue is that its not (just) docx4j using SAX, but dependent libs

**Comment by roded** [comment]
I understand.
Then I'll have to battle w/ the application server to make is find the same factory.
Thanks.
