### ISSUE TITLE
MainDocumentPart.getStylesInUse() changes document elements' parent property

### ISSUE THREAD

**Issue by roded** [plutext/docx4j#191]
`XHTMLImporterImpl`'s `stylesToCSS()` drills down to `MainDocumentPart`'s `getStylesInUse()`.
When `getStylesInUse()` traverses the document, it passes a `List<Object>` as the traversed element.
This causes issues for further processing of the element tree since elements whose parent is the `MainDocumentPart` have their parent set as the `List<Object>` traversed by `getStylesInUse()`.
Is this intended? Can the alteration of the element tree be avoided in this case?

**Comment by plutext** [comment]
Because of https://github.com/plutext/docx4j/blob/master/src/main/java/org/docx4j/TraversalUtil.java#L124 ?

**Comment by roded** [comment]
Yep

**Comment by plutext** [comment]
so what's an example of where this does the wrong thing?

**Comment by roded** [comment]
`WordprocessingMLPackage wordPackage = ...;
MainDocumentPart mainDocumentPart = wordPackage.getMainDocumentPart();
Set<String> stylesInUse = mainDocumentPart.getStylesInUse();`

Pre the `getStylesInUse()` call, the `MainDocumentPart`'s content element had as their parent the 'org.docx4j.wml.Body' object.
Post the `getStylesInUse()` call, their parent is the `MainDocumentPart`'s content `List`.

**Comment by plutext** [comment]
https://github.com/plutext/docx4j/commit/1e5768a941e0579c377b745fed3c3687d5f6ecfa

**Comment by roded** [comment]
Thanks!
(Is there an ETA on 3.2.3?)

**Comment by plutext** [comment]
http://www.docx4java.org/forums/announces/docx4j-3-3-0-release-candidate-please-try-it-t2379.html
