### ISSUE TITLE
Outputstream is closed if conversion fails

### ISSUE THREAD

**Issue by uffew** [plutext/docx4j#193]
When converting a docx document which is somehow corrupted an `Exception` is thrown in the class `AbstractExporter` in the function `export.` There is a finally block in that function that closes the `Outputstream.` This means that it is impossible to write anything else to the `Outputstream.`
This must be a mistake. The `Outputstream` is something external passed in to the `toHTML` function and it should not be closed by Docx4j.

**Comment by plutext** [comment]
https://github.com/plutext/docx4j/commit/7575b3442cd136999b628ab8b75a8b18a3941b7e
