### ISSUE TITLE
NullPointerException in variableReplace

### ISSUE THREAD

**Issue by akitaylor** [plutext/docx4j#200]
The XmlUtils.replace method throws NullPointerException in case it finds a key in the template that is not contained by the "mappings" map. This is clearly not intended accorind to the following code.

XmlUtils:520-524:
	       **String val = mappings.get(key).toString();**
	       if (val==null) {
	    	   log.warn("Invalid key '" + key + "' or key not mapped to a value");
	    	   strB.append(key );
	       }

The solution is to remove toString call in line 520.

**Comment by plutext** [comment]
Already fixed by https://github.com/plutext/docx4j/commit/a780cb508c163b230a8df4cb5c8dadff2cf8cb97
thanks!

**Comment by akitaylor** [comment]
Thanks, I'm glad it is already fixed. 

But the problem highlights another problem, that is still present, namely the Word tends to insert various tags in the key string so it will look like this for example:
`</w:t></w:r><w:r w:rsidR="00DD2DA2" w:rsidRPr="005E4F56"><w:t>my</w:t></w:r><w:r w:rsidRPr="005E4F56"><w:t>K</w:t></w:r><w:r w:rsidR="00862434" w:rsidRPr="005E4F56"><w:t>ey</w:t></w:r><w:r w:rsidR="00B119E9" w:rsidRPr="005E4F56"><w:t>`

The key would be "myKey" in this example.

In this case the replacement will fail and these tags cannot always be removed even by using "Clear all formatting" Word function. That's why I propose to process the key string for example with the following:
key.replaceAll("<[/]?w([^/>]*)[/]?>","");

Thanks,
Akos

Ps: it would be also fine to access snapshot version in maven repository.
