### ISSUE TITLE
Indentation in file document.xml

### ISSUE THREAD

**Issue by jdm75** [plutext/docx4j#213]
I recently upgraded to Docx4j v3.2.2 and noticed that WordprocessingMLPackage.save method now generates a document.xml file in the saved .docx that is indented.
Such documents work ok with Microsoft Word and LibreOffice, but not with OpenOffice (the document appears with many extra spaces).

**Comment by plutext** [comment]
Interesting.  Which version of OO is that?

There is the following docx4j property:

# Whether to pretty print XML parts (defaults to true)
# since docx4j 3.2.0
docx4j.jaxb.formatted.output=false

Sample docx4j.properties is at https://github.com/plutext/docx4j/blob/master/src/samples/_resources/docx4j.properties

Please re-open if this doesn't solve the issue.

**Comment by jdm75** [comment]
Thank you for your quick reply. I did no see any change when I set the proerty docx4j.jaxb.formatted.output to false. I tried to add a docx4j.properties into my project resources and also to set the property with System.setProperty but the xml is still pretty-printed. I could not find documentation on how to set docx4j properties, may be I am doing something wrong ? BTW the Open Office version is a recent one : 4.1.1

**Comment by plutext** [comment]
Do you have logging operational?   org.docx4j.utils.ResourceUtils logs
about its success or otherwise in loading docx4j.properties

DEBUG org.docx4j.utils.ResourceUtils .getResource line 70 - Attempting to
load: docx4j.properties

It will log at WARN level if that can't be done

**Comment by jdm75** [comment]
Yes. It is loading my property file. I debug in Docx4jProperties class and saw that the property gets loaded however it does not seem to be used. I also tried Docx4jProperties.setProperty("docx4j.jaxb.formatted.output", "false") without success

**Comment by plutext** [comment]
Try Docx4jProperties.setProperty("docx4j.jaxb.formatted.output", false) ie
with a boolean not string arg.

In JaxbXmlPart, we have:

    public void marshal(java.io.OutputStream os, Object
namespacePrefixMapper) throws JAXBException {


try {
Marshaller marshaller = jc.createMarshaller();
if (Docx4jProperties.getProperty("docx4j.jaxb.formatted.output", true)) {
marshaller.setProperty("jaxb.formatted.output", true);
}

so it should work... it certainly works for me in docx4j v3.3.1  (in 3.3.1
it only pretty prints if docx4j.jaxb.marshal.canonicalize=false).  I tested
using MOXy, but Sun/Oracle JAXB ought to be the same.

**Comment by jdm75** [comment]
I confirm: property docx4j.jaxb.formatted.output is ignored in version 3.2.2 but works ok in 3.3.1. Thanks
