### ISSUE TITLE
extracting an embedded file from DOCX does not work properly

### ISSUE THREAD

**Issue by Omnipresent** [plutext/docx4j#222]
I have a DOCX document which contains an embedded XLSX file in it. I am using docx4j (2.7.1) to extract the embedded XLSX and I'm saving it on the disk. I am able to extract and save the embedded XLSX to the disk using docx4j but it seems that the contents of the embedded file are not what is expected. 

Attached are the sample DOCX (with an XLSX embedded in it). Also, the embedded XLSX in its original form. 
[Docx_with_xlsx_in_it.docx](https://github.com/plutext/docx4j/files/576349/Docx_with_xlsx_in_it.docx)
[simpleXLSXtest.xlsx](https://github.com/plutext/docx4j/files/576348/simpleXLSXtest.xlsx)

This is the code I use to extract the embedded XLSX from the DOCX and save it to disk:

```
FileInputStream is = new FileInputStream(new File("Docx_with_xlsx_in_it.docx"))
WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(is)
for (Entry<PartName, Part> entry : wordMLPackage.getParts().getParts().entrySet()) {
    String extension = ((PartName) entry.getKey()).getExtension()
    if (extension.equalsIgnoreCase("xlsx")) {
       log.debug("Found a linked file with extension: " + extension)
       FileOutputStream fos = new FileOutputStream("Somefile.xlsx")
       ((BinaryPart)entry.getValue()).writeDataToOutputStream(fos);
    }
}
```

[Somefile.xlsx](https://github.com/plutext/docx4j/files/576364/Somefile.xlsx)

Attached below is the extracted XLSX. Observe that opening the file below (`Somefile.xlsx`) opens excel but the contents of the XLSX are never shown. Additionally, opening the embedded XLSX in its original form `simpleXLSXtest.xlsx` in a text program (like SublimeText) shows `1739` lines, whereas opening the extracted embedded XLSX (`Somefile.xlsx`) shows `1728` lines.

**Comment by plutext** [comment]
I think your code is probably OK; I didn't try running it.

What I did was extract the embedded XLSX using a zip tool.  I see it is
"strange" when you look at it in Excel.

If you compare it to the original, there are 2 differences in workbook.xml:

  <fileVersion appName="xl" lastEdited="5" lowestEdited="5"
rupBuild="25203"/>
  <workbookPr showInkAnnotation="0" autoCompressPictures="0"/>
  <bookViews>
    <workbookView visibility="hidden" xWindow="240" yWindow="240"
windowWidth="25360" windowHeight="17220" tabRatio="500"/>
  </bookViews>
  <sheets>
    <sheet name="Sheet1" sheetId="1" r:id="rId1"/>
  </sheets>
  <calcPr calcId="140000" concurrentCalc="0"/>
  <oleSize ref="A1"/>
  <extLst>
    <ext uri="{7523E5D3-25F3-A5E0-1632-64F254C22452}" xmlns:mx="
http://schemas.microsoft.com/office/mac/excel/2008/main">
      <mx:ArchID Flags="2"/>
    </ext>
  </extLst>
</workbook>

Difference one:  workbookView/@visibility="hidden"

Difference two: oleSize element.

I removed workbookView/@visibility, and found the xlsx displayed as
expected in Excel.

If on review of your code, you think docx4j added that incorrectly, please
open another bug showing steps to reproduce.
