### ISSUE TITLE
wp14:editId and wp14:anchorId in headers

### ISSUE THREAD

**Issue by stewmorg** [plutext/docx4j#225]
I'm seeing an issue with documents generated wiht docx4j 3.3.1 where a header part has wp14:editId and wp14:anchor tags added to a wp:anchor along with:

`<wp14:sizeRelH relativeFrom="margin">
                        <wp14:pctWidth>0</wp14:pctWidth>
                    </wp14:sizeRelH>
                    <wp14:sizeRelV relativeFrom="margin">
                        <wp14:pctHeight>0</wp14:pctHeight>
                    </wp14:sizeRelV>`

The resulting header part definition doesn't contain an mc:ignorable, but the maindocument part does:

`mc:Ignorable="w14 w15 wp14"`

This results in a corrupted file being created (according to word 2007).  Editing the header.xml files manually to add the ignoreable flag back into each part removes the error.

**Comment by plutext** [comment]
Thanks for the report.

Could you please try http://www.docx4java.org/docx4j/docx4j-nightly-20161130.jar

**Comment by plutext** [comment]
Note, you still need to do something like:  		headerPart.getContents().setIgnorable("wp14");
