### ISSUE TITLE
Non-breaking hyphen (\u2011) is not rendered correctly when binding to content controls

### ISSUE THREAD

**Issue by roytmana** [plutext/docx4j#229]
Some of my data that I bind to content control needs non-breaking hyphens (\u2011)
It renders fine in content controls (if I inject XML and then bind it to content control) but when I use bind XML + Remove  content control option it renders incorrectly. in MS Word 2013 it renders wits some sort of white space and it does not act as non-breaking in MW Word 2010 it renders as unknow character

MSWord 2013:
![image](https://cloud.githubusercontent.com/assets/2524911/21835574/ff2bcb5e-d78b-11e6-9127-b7a8de93ea89.png)

MSWord 2010
![image](https://cloud.githubusercontent.com/assets/2524911/21835553/dadd0060-d78b-11e6-8d85-9a0bd1195350.png)

while in content control it renders and behaves just fine:
![image](https://cloud.githubusercontent.com/assets/2524911/21835593/3b398604-d78c-11e6-9fff-c225366d509b.png)

**Comment by plutext** [comment]
See http://www.docx4java.org/forums/docx-java-f6/non-breaking-hyphen-u2011-is-not-rendered-correctly-when-t2514.html
