### ISSUE TITLE
Conversion exception when the template document has complex path binding with jre using not english locale

### ISSUE THREAD

**Issue by ai-github** [plutext/docx4j#232]
If there is a complex xpath (it is considered complex when there are some boolean xpaths with "=", "<", ">" and count() [taken from XmlPart]) and jre uses not english locale then wrapped Docx4JException (with TransformerException) is thrown because original XPathException has translated message. It happens because the code in cachedXPathGetString(String xpath, String prefixMappings) method in XmlPart class checks message of excpetion to contain string in english only (message of exception should contain "Can not convert #BOOLEAN").  
There is a workaround - add java options for jre to use english locale: -Duser.country=EN -Duser.language=en
Tested on Apahce Tomcat with OpenDoPE server using docx4j 3.3.2

**Comment by plutext** [comment]
Fixed by https://github.com/plutext/docx4j/commit/76b86aa3273ebab189abd040f8fa77df0b91d097
Will be in v3.3.3
