### ISSUE TITLE
Null pointer exception, convertAltChunks(), JaxbXmlPartAltChunkHost.java:193

### ISSUE THREAD

**Issue by jjl71** [plutext/docx4j#233]
**Using docx4j-3.3.2**

**Error:**
java.lang.NullPointerException at  org.docx4j.openpackaging.parts.JaxbXmlPartAltChunkHost.convertAltChunks(JaxbXmlPartAltChunkHost.java:193)
	at test.main(test.java:54)

The error occurs using the following test code. Could _afip.getAltChunkType();_ in some cases return something that     _if (type.equals(AltChunkType.Xhtml) )_ cannot handle?

**Sample code:**
String inputfilepath = new String("/home/username/testing.docx");
try {
    WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(new java.io.File(inputfilepath));
    MainDocumentPart mdp = wordMLPackage.getMainDocumentPart(); 
    WordprocessingMLPackage pkgOut = mdp.convertAltChunks(); // Display result 
    //System.out.println(XmlUtils.marshaltoString(pkgOut .getMainDocumentPart().getJaxbElement(), true, true)); 
    } catch (Exception e) {
	e.printStackTrace();
}

**Lines in JaxbXmlPartAltChunkHost**
line:191	AltChunkType type = afip.getAltChunkType();

line: 193  if (type.equals(AltChunkType.Xhtml) ) {

Attaching a document file for possible testing purposes. Note, the attached document has been generated using DocxFactory (python) and has never been opened in MS Word.  Word opens the file without any issues though.

I hope this is worth opening an issue, would have posted on the forum first, but could not manage to get registered there (no verification e-mail).

[testing.docx](https://github.com/plutext/docx4j/files/736950/testing.docx)

**Comment by plutext** [comment]
Thanks for this; now fixed by https://github.com/plutext/docx4j/commit/911b9baa648508e229977777894d0bfd1733f140

Please note docx4j doesn't convert altChunks of type html or mht; you need to convert them to xhtml first with a tidy program of your choice.
