### ISSUE TITLE
XmlPart heuristic introduce unexpected behaviour

### ISSUE THREAD

**Issue by ThomBi** [plutext/docx4j#235]
Hi,

The quick n dirty heuristic (docx4j v3.3.3) to try to avoid falling through to the catch block in lines 204-265 of the XmlPart leads to unexpected results of XPath expressions.

XPath expressions containing a '=' sign like 
- substring('X', 2 - number(/order/priceType/@key = 'P'))
- /header/valueobject[@name='Order']/currency
result in 'true' or 'false' and does not return the XPath result.

log output:
INFO   [BindingTraverserXSLT] /header/valueobject[@name='Order']/currency yielded result 'true'
...
INFO   [BindingTraverserXSLT] substring('X', 2 - number(/order/priceType/@key = 'P')) yielded result 'false'

The used heuristic doesn't consider the position of the '=' sign within predicates nor combined xpath expressions.

Thanks,
T.

**Comment by plutext** [comment]
Please try http://www.docx4java.org/docx4j/docx4j-nightly-20170228.jar

**Comment by ThomBi** [comment]
Hi,

thank you. The xpath now return the expected results.

Best regards,
T.

**Comment by plutext** [comment]
Great, thanks for confirming.
