### ISSUE TITLE
Docx to HTML fails in ordering the elements

### ISSUE THREAD

**Issue by SelvaSurukam** [plutext/docx4j#253]
Hi Team,

I am using latest version of `docx4j`, when I tried to convert `docx` to `html`, The order of paragraph mismatch in converted `html`.

PFA for sample `docx` and converted `html`.

[sample.docx](https://github.com/plutext/docx4j/files/1094663/sample.docx)
[sample_converted_html.txt](https://github.com/plutext/docx4j/files/1094662/sample_converted_html.txt)

**Comment by plutext** [comment]
I guess you performed the conversion using nestLists=true:

    	// list numbering:  depending on whether you want list numbering hardcoded, or done using <li>.
    	if (nestLists) {
    		SdtWriter.registerTagHandler("HTML_ELEMENT", new SdtToListSdtTagHandler());
    	} else {
    		htmlSettings.getFeatures().remove(ConversionFeatures.PP_HTML_COLLECT_LISTS);
    	}

set it to false instead.
