### ISSUE TITLE
Font Size is 50% of the provided value in RPr

### ISSUE THREAD

**Issue by drewsmith** [plutext/docx4j#254]
I'm customizing the font size using the run properties of a Paragraph and noticed that the font size was half of what I'm setting when saving the document:

```
MainDocumentPart documentPart = wordMLPackage.getMainDocumentPart();
StyleDefinitionsPart stylePart = documentPart.getStyleDefinitionsPart();

org.docx4j.wml.Style drewsStyle = new org.docx4j.wml.Style();
drewsStyle.setStyleId("drews_sweet_style");
drewsStyle.setCustomStyle(true);
drewsStyle.setType("paragraph");

RPr runProperties = new RPr();

Color fontColor = new Color();
fontColor.setVal("FF0000"); // red
runProperties.setColor(fontColor);

RFonts fontFamily = new RFonts();
fontFamily.setAscii("Verdana");
fontFamily.setHAnsi("Verdana");
runProperties.setRFonts(fontFamily);

runProperties.setI(new BooleanDefaultTrue()); // italic
runProperties.setB(new BooleanDefaultTrue()); // bold

HpsMeasure fontSize = new HpsMeasure();
fontSize.setVal(BigInteger.valueOf(36 * 2));
runProperties.setSz(fontSize);

drewsStyle.setRPr(runProperties);

org.docx4j.wml.Style.Name styleName = new org.docx4j.wml.Style.Name();
styleName.setVal("Drew's Sweet Style");
drewsStyle.setName(styleName);

sdp.getJaxbElement().getStyle().add(drewsStyle);

P paragraph = documentPart.createStyledParagraphOfText("drews_sweet_style", "Some sweet text");
documentPart.getContent().add(paragraph);

wordMLPackage.save(new File("/Users/drew/Desktop/testing.docx"));
```

<img width="1029" alt="screen shot 2017-06-22 at 10 41 25 pm" src="https://user-images.githubusercontent.com/595469/27465884-f6cdc738-579b-11e7-8e29-2145cd075588.png">

If I change the font size to ```fontSize.setVal(BigInteger.valueOf(36));``` the font size is 18:

<img width="1029" alt="screen shot 2017-06-22 at 10 43 44 pm" src="https://user-images.githubusercontent.com/595469/27465917-44b94238-579c-11e7-9002-e35904ff929d.png">

Here's an example with an odd font size (21):

<img width="1029" alt="screen shot 2017-06-22 at 10 44 53 pm" src="https://user-images.githubusercontent.com/595469/27465951-7780e50e-579c-11e7-98de-9baf5fb610af.png">

**Comment by drewsmith** [comment]
Quick follow up. This might be a Word issue. Here's my style from styles.xml:
```
<w:style w:type="paragraph" w:styleId="drews_sweet_style" w:customStyle="true">
        <w:name w:val="Drew's Sweet Style"/>
        <w:basedOn w:val="Normal"/>
        <w:rPr>
            <w:rFonts w:ascii="Verdana" w:hAnsi="Verdana"/>
            <w:b/>
            <w:i/>
            <w:color w:val="FF0000"/>
            <w:sz w:val="21"/>
        </w:rPr>
    </w:style>
```

**Comment by plutext** [comment]
The unit is half points: http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/sz_1.html

So things are working as expected/intended, its just that your assumptions are wrong ;-)

**Comment by drewsmith** [comment]
Ha. Thanks for correcting me.
