### ISSUE TITLE
NullPointerException in Load3

### ISSUE THREAD

**Issue by jimka** [plutext/docx4j#265]
Hi,

I'm getting a NullPointerException for some Word-documents.

The NPE is happening in the Load3-class att line 445, specifically this line: 

```
....
443: part = ctm.getPart("/" + resolvedPartUri, rel);
444: 
**445: log.debug("ctm returned " + part.getClass().getName() );**
446:
447: if (part instanceof org.docx4j.openpackaging.parts.ThemePart
...
```

If you're asking me this should be something like:

`445: log.debug("ctm returned " + (part != null ? part.getClass().getName() : "null") );`

**Comment by plutext** [comment]
looks like the null test at 595 should be moved before 445

**Comment by jimka** [comment]
It would be preferable that docx could handle documents where parts like these are missing. As it is now, the library flat out refuses to load said documents. It instead throws an NPE and aborts load.

**Comment by plutext** [comment]
Your document is broken.  How was it created?
We could have a doc4j property which enables the behaviour you describe, but given that no popular products create such broken documents, there has been little demand for this.
As things stand, it should be throwing Docx4JException, not an NPE, so that's a bug.

**Comment by jimka** [comment]
That might very well be the case, The document can be opened in Word though.

The document was created in Word, but manipulated by one of our tools. The document is a result of merging one document with another.

I've been digging some more in the affected document, and it seems that all of the images that should be in the document, are missing. This does not happen to all documents though, only a very small minority.

The NPE seems to be a result of the following in /word/_rels/header1.xml.rels:
`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="NULL"/>`
**Target** should obviously not be null.

The following code is used to copy images from one document to another, perhaps you can identify what the problem might be?

```
    private void copyImages(Base src, Base dst) throws InvalidFormatException {
        Map<String, String> idMap = new HashMap<>();
        Map<String, List<CTBlip>> blipMap = new HashMap<>();

        for (Relationship rel : src.getRelationshipsPart().getRelationships().getRelationship()) {
            if (!rel.getType().equals("http://schemas.openxmlformats.org/officeDocument/2006/relationships/image")) {
                continue;
            }

            BinaryPart part = (BinaryPart) src.getRelationshipsPart().getPart(rel);

            BinaryPart imagePart = new BinaryPart(new PartName(part.getPartName().getName()));
            imagePart.setBinaryData(part.getBuffer());
            imagePart.setContentType(new ContentType(part.getContentType()));
            imagePart.setRelationshipType(Namespaces.IMAGE);

            Relationship imagePartRelationship = dst.addTargetPart(imagePart);
            idMap.put(rel.getId(), imagePartRelationship.getId());
        }

        getAllElementFromObject(dst, Drawing.class).forEach(d -> {
            List<Object> list = d.getAnchorOrInline();
            for (Object anchorOrInline : list) {
                final Graphic graphic;
                if (anchorOrInline instanceof Anchor) {
                    Anchor a = (Anchor) anchorOrInline;
                    graphic = a.getGraphic();
                } else if (anchorOrInline instanceof Inline) {
                    Inline i = (Inline) anchorOrInline;
                    graphic = i.getGraphic();
                } else {
                    graphic = null;
                }

                if (graphic == null) {
                    continue;
                }

                final GraphicData graphicData = graphic.getGraphicData();
                if (graphicData == null) {
                    continue;
                }

                final Pic pic = graphicData.getPic();
                if (pic == null) {
                    continue;
                }

                final CTBlipFillProperties blipFill = pic.getBlipFill();
                if (blipFill == null) {
                    continue;
                }

                final CTBlip blip = blipFill.getBlip();
                if (blip == null) {
                    continue;
                }

                final String id = blip.getEmbed();

                List<CTBlip> blips = blipMap.get(id);
                if (blips == null) {
                    blips = new ArrayList<>();
                    blipMap.put(id, blips);
                }

                blips.add(blip);
            }
        });

        blipMap.entrySet().forEach(es -> es.getValue().forEach(b -> b.setEmbed(idMap.get(es.getKey()))));
    }
```

**Comment by plutext** [comment]
I guess your image part names are not distinct?  (eg you have image1.png in each of the documents you are merging).  addTargetPart has an optional arg you should look into

**Comment by jimka** [comment]
Reading the code, the default behaviour is to overwrite. So name-collision shouldn't result in all images missing. Or is there something that I'm missing?

**Comment by plutext** [comment]
You say you have <Relationship ... Target="NULL"/>.  I assume that is what you see when you unzip the docx saved by docx4j?    Try turning on debug level logging, maybe for org.docx4j.openpackaging.io3.Save  and RelationshipsPart
