### ISSUE TITLE
Plugin  Docx4j_Helper_3-3-1-03.exe  Not found

### ISSUE THREAD

**Issue by otaviosgoncalves** [plutext/docx4j#267]
Where I can found the the plugin :  http://www.plutext.com/dn/downloads/1472868282152/Docx4j_Helper_3-3-1-03.exe ?

The url above return Http 410 - Gone.
I get this URL in https://www.docx4java.org/blog/2016/05/docx4j-helper-word-addin-new-version-v3-3-0/
Someone have a URL wich I can use ?

**Comment by plutext** [comment]
https://www.plutext.com/dn/downloads/1504171638488/Docx4j_Helper_3-3-6-0.exe

**Comment by vbaidak** [comment]
Hi!

This url is broken:
http://www.plutext.com/dn/downloads/1472868282152/Docx4j_Helper_3-3-1-03.exe?_ga=2.224088786.837929860.1604649493-60107745.1601964072

Could you please share the working one?

**Comment by plutext** [comment]
https://www.docx4java.org/docx4j/Docx4j_Helper_8-2-1-1.exe

Please see further https://www.docx4java.org/forums/announces/docx4j-helper-addin-new-installer-available-t2946.html

**Comment by onkar-indellient** [comment]
Hi the above links are not working anymore. Can anyone share the updated link please?
