### ISSUE TITLE
How do I convert a .doc file to pdf?

### ISSUE THREAD

**Issue by l0v3w4v3** [plutext/docx4j#286]
I need to convert a doc file to pdf. I tried using POI to convert it to .docx first then using Docx4J to convert to pdf, but I got the error at the line "wordprocessingMLPackage.load(is)"

			`// POI: Convert doc to XSL FO
			HWPFDocument doc = new HWPFDocument(new FileInputStream(file));
			WordToFoConverter wordToFoConverter = new WordToFoConverter(
				XMLHelper.getDocumentBuilderFactory().newDocumentBuilder().newDocument());
			wordToFoConverter.processDocument(doc);

			// XSL FO to XSL FO?!
			org.w3c.dom.Document document = wordToFoConverter.getDocument();
			ByteArrayOutputStream outputFO = new ByteArrayOutputStream();
			Source source = new DOMSource(document);
			Result output = new StreamResult(outputFO);
			TransformerFactory.newInstance().newTransformer().transform(source, output);
			InputStream is = new ByteArrayInputStream(outputFO.toByteArray());

			WordprocessingMLPackage wordprocessingMLPackage = new WordprocessingMLPackage();
			wordprocessingMLPackage.load(is);

			String outputPath = "output.pdf";
			OutputStream os = new FileOutputStream(outputPath);
			Docx4J.toPDF(wordprocessingMLPackage, os);
			os.close();`

The error is 

> javax.xml.bind.UnmarshalException: unexpected element (uri:"http://www.w3.org/1999/XSL/Format", local:"root"). Expected elements are <{http://schemas.microsoft.com/office/2006/xmlPackage}package>,<{http://schemas.microsoft.com/office/2006/xmlPackage}xmlData>

Anyone help?

**Comment by plutext** [comment]
Looks like you are feeding docx4j an XSL FO document, not a docx file. 

An alternative to this tool chain would be Plutext's commercial doc/docx to PDF Converter, which can read binary .doc files.  For more, please see https://converter-eval.plutext.com/

**Comment by l0v3w4v3** [comment]
@plutext may the tool work when I do not have internet connection?

**Comment by l0v3w4v3** [comment]
@plutext I thought the error is XSL FO document format doesn't match Office 2006 requirement so the WordprocessingMLPackage could not load it. I saw this line in the above site "From version 3.3.0, docx4j uses the PDF Converter by default." and I am using docx4j 3.3.6 so do I still need to try this? Or is there any other way?

**Comment by plutext** [comment]
docx4j can't load an XSL FO document.

It can't load a doc file either, so if you want to convert doc to PDF, do that using the converter API (not docx4j):  https://github.com/plutext/PDF-Converter-Java/blob/master/src/sample/java/Sample.java
