### ISSUE TITLE
FlatOpcXmlImporter class format excel flat opc xml

### ISSUE THREAD

**Issue by QuentinBoBoeree** [plutext/docx4j#295]
so,i need help.I search it with all methods,but no results.SpreadsheetMLPackage how to load flat opc xml.I saw the FlatOpcXmlImporter class description,but no sample.Anybody know it,and give me a example what excel flat opc xml.

**Comment by QuentinBoBoeree** [comment]
@plutext

**Comment by QuentinBoBoeree** [comment]
nobody know that?

**Comment by plutext** [comment]
Something like https://github.com/plutext/docx4j/blob/master/src/samples/docx4j/org/docx4j/samples/ConvertInFlatOpenPackage.java
