### ISSUE TITLE
Please update the documentation about toc numbering calling your webservice

### ISSUE THREAD

**Issue by maxiplay** [plutext/docx4j#307]
I discovered  [here](https://www.docx4java.org/forums/docx-java-f6/toc-update-doesn-t-work-2-t2490.html ) with a sad surprise that the table of content numbering update need to call a pdf generation service at this [adress](http://converter-eval.plutext.com:80/v1/00000000-0000-0000-0000-000000000000/convert).  

Today the library say this when update the toc.

Caused by: org.docx4j.toc.TocException: Error in toc web service at http://converter-eval.plutext.com:80/v1/00000000-0000-0000-0000-000000000000/convert
 HTTP response: 301 Moved Permanently
	at org.docx4j.toc.TocGenerator.getPageNumbersMapViaService(TocGenerator.java:710) ~[docx4j-3.3.6.jar:na]
	at org.docx4j.toc.TocGenerator.getPageNumbersMap(TocGenerator.java:663) ~[docx4j-3.3.6.jar:na]
	at org.docx4j.toc.TocGenerator.populateToc(TocGenerator.java:438) ~[docx4j-3.3.6.jar:na]
	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:342) ~[docx4j-3.3.6.jar:na]
	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:561) ~[docx4j-3.3.6.jar:na]
	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:509) ~[docx4j-3.3.6.jar:na]
	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:489) ~[docx4j-3.3.6.jar:na]

It seems the service moved.

I understand the technical need to do this, but I think very strange and obscur that you don't specify it in documentation. 

I choose this library reading the documentation, saying the  the toc numbering update is possible. I almost sent in production my code without knowing that docx that i generate are sent to an unknow webservice. => confidentiality issue.

I have my own custom service to transform docx to pdf and i would like to know if it's possible to call it without call your server or use  XSL FO based output.

I would like also say that when I add XSL FO jar the docx generation failed. Is it always updated ?

thanks

**Comment by maxiplay** [comment]
Next question : Do you use other call to your webservice conversion for orther features ?

**Comment by plutext** [comment]
Sorry for the outdated documentation!  Now updated at https://github.com/plutext/docx4j/commit/92938b2b40da5f38ef821385a04d121a4a512fa1

ToC page number generation needs to know where the page breaks fall, and for this we typically use the layout engine in the commercial PDF Converter (described at page 20 of Getting Started).  As it says there, you can/should install your own instance.

It is used unless you have FOExporterVisitor/FOP on your classpath:
```
    	if (Docx4J.pdfViaFO()) {
    		return getPageNumbersMapViaFOP();
    	} else {
    		// recommended
    		return getPageNumbersMapViaService();
    	}
```

The port was altered to 443 at https://github.com/plutext/docx4j/commit/2d358ff37891554ac3ef1a992f74a7ab43cef1eb#diff-d780ba5dcfd2a642f1f4dc1adee51e5d and https://github.com/plutext/docx4j/commit/330118ec9e8392139d3184f1be3cdb7c4d3b6dd1#diff-aabef31b0b313b56b8286d84fc64e904 some months ago.

ToC page numbering and PDF output are the only 2 things docx4j potentially uses the web service for.  As mentioned above, you can/should install your own instance.  But if you don't like either of those options, put export-FO onto your classpath.
