### ISSUE TITLE
Convert XML to human readable with all fonts and style

### ISSUE THREAD

**Issue by rohitgarg29** [plutext/docx4j#310]
Hi friends,

I am trying to make the docx4j working for Android platform but I am stuck where I have to convert the XML to proper string format with all the fonts and styles. Please guide me with small example as I recently started on it. THANKS

Regards,
Rohit

**Comment by plutext** [comment]
Not sure what you mean.

When you say XML, do you mean WordML, for example:

```
       <w:p >
            <w:pPr>
                <w:pStyle w:val="Heading1"/>
            </w:pPr>
            <w:r>
                <w:t xml:space="preserve">The quick </w:t>
            </w:r>
            <w:r >
                <w:rPr>
                    <w:color w:themeColor="accent4" w:themeShade="BF" w:val="BF8F00"/>
                </w:rPr>
                <w:t xml:space="preserve">brown </w:t>
            </w:r>
            <w:r >
                <w:rPr>
                    <w:rFonts w:ascii="Comic Sans MS" w:hAnsi="Comic Sans MS"/>
                </w:rPr>
                <w:t>fox</w:t>
            </w:r>
        </w:p>
```

And when you say "proper string format", you mean what?

**Comment by rohitgarg29** [comment]
Hi @plutext ,

Thanks for your quick reply. I am using the document  to get the Text, styling, font size etc. I have used the below code to get the text but styling is not coming. 

WordprocessingMLPackage wordMLPackage = (WordprocessingMLPackage)loader.get(is);
MainDocumentPart documentPart = wordMLPackage.getMainDocumentPart();
String XML = XmlUtils.marshaltoString(documentPart.getJaxbElement(), true, true);
String textValue = "";
String textNodesXPath = "//w:t";
List<Object> textNodes= documentPart.getJAXBNodesViaXPath(textNodesXPath, true);
for (Object obj : textNodes) {
     Text text = (Text) ((JAXBElement) obj).getValue();
      textValue = textValue + text.getValue();
 }            

Yes, you are correct, I meant WordML. By proper string format, I meant new lines, tabs, styling, font size etc.

**Comment by plutext** [comment]
Still not clear what string format you have in mind?!

In your code, String XML will hold the directly applied formatting.

https://www.docx4java.org/forums/docx-java-f6/word-2016-docx-outlinelvl-is-always-null-t2702.html might help regarding formatting which is defined in a style.

**Comment by rohitgarg29** [comment]
[Sonika.docx](https://github.com/plutext/docx4j/files/2222636/Sonika.docx)

I am trying to set the text of the attached document in TextView/EditText. I am able to extract the text but it looks like as screeenshot (attached). I want the formatting like font color, font size, next line, table as it looks in the docx file. I hope I am understandable now. 

![screenshot_20180724-121112](https://user-images.githubusercontent.com/17814841/43125348-c955e682-8f3a-11e8-9410-4bc52ebd1840.png)

**Comment by plutext** [comment]
Well, for that you need to open the docx in a suitable app on the device, convert to HTML or PDF, or implement your own docx viewer...
