### ISSUE TITLE
10MB Docx file takes more time to convert pdf

### ISSUE THREAD

**Issue by bhaveshkharwa** [plutext/docx4j#317]
HI,

Convert 10MB Docx file takes more time to convert pdf. Also is there any options to get first page of doc and convert it into PDF.

Following code snippets to convert docx file to pdf
`<dependency>
			<groupId>org.docx4j</groupId>
			<artifactId>docx4j</artifactId>
			<version>6.0.1</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.commons</groupId>
					<artifactId>commons-compress</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
`
`
ByteArrayOutputStream bos = new ByteArrayOutputStream();
				System.out.println("Start : "+new Date());
				WordprocessingMLPackage wordprocessingMLPackage = WordprocessingMLPackage.load(bis);
				Docx4J.toPDF(wordprocessingMLPackage, bos);
				System.out.println("End : "+new Date());
`

**Comment by plutext** [comment]
Are you using Plutext's commercial converter, or do you have export-FO on your classpath?

If the former, please email support@plutext.com

**Comment by bhaveshkharwa** [comment]
I have added only docx4j dependency in maven. Not added other dependencies.
