### ISSUE TITLE
TocStyles compares basedOn to "Normal" but basedOn is a style id while "Normal" is a style name

### ISSUE THREAD

**Issue by vsch** [plutext/docx4j#319]
basedOn property is a style id which will can be localized by Word and will not equal "Normal". For example in the German version of Word it is "Standard". 

The line: `clone.getBasedOn().getVal().equals("Normal")` should convert the style name to id before testing.

Similarly for `!defaultPStyleId.equals("Normal")`.

https://github.com/plutext/docx4j/blob/master/src/main/java/org/docx4j/toc/TocStyles.java#L178-L180

**Comment by plutext** [comment]
Please see comment added 
 at https://github.com/plutext/docx4j/commit/cf89ed023a95fe9b6fdd5a76fab0c31f695addbc

It says:

> Our default TOC styles assume a style with ID "Normal" is present.
> There are 2 cases to consider:
> Case 1: user is using default TOC styles, with a non-English docx (so their document default style is something else)
> Case 2: user has substituted their own TOC styles (ie with localised style id).
> We don't worry about case 2 here.  User is responsible for ensuring the TOC styles are consistent with their document (ie are basedOn a style id present in their styles part)

The code you pointed to handles case 1.

**Comment by vsch** [comment]
I see the logic now. Thanks.

**Comment by plutext** [comment]
No worries :-)
