### ISSUE TITLE
Thrown Exceptions also get logged.

### ISSUE THREAD

**Issue by P2EQgf** [plutext/docx4j#320]
Short version: If an exception is thrown, it doesn't need to be logged since throwing the exception is the error handling. If the exception needs to be logged its the responsibility of the part of code that catches it (and does not throw again).

Long version: In my project a user can upload a file which is converted. However, if the docx file is invalid an exception is thrown. So far no problem, we just catch it and tell the user we cannot convert it and move on from there. However, the docx4j.openpackaging.packages.OpcPackage also logs the entire stacktrace on the error log level. Suddenly an operation that is working as intended creates a ton of log output on error. Disabling the entire log for that package seems like a bad option because we might miss valid and possibly important log outputs, but if we don't do that our logs will be cluttered by stacktraces where nothing bad happened.

I took a short look at the stacktrace and it seems like at multiple points in the code an exception is caught, logged (sometimes wrapped in another exception) and then thrown again. Just don't log it, if someone wants to have that log he should do it himself.

**Comment by plutext** [comment]
Thanks for this.  I've addressed it in OpcPackage: https://github.com/plutext/docx4j/commit/a3d7fde0f415a33cc965bfa296951aad4d826cd2

Leaving this open for now in case there is somewhere else causing you grief, you'd like to point out.

**Comment by P2EQgf** [comment]
Well, I didnt intend to close this. But might as well be closed.
