### ISSUE TITLE
how to store WordprocessingMLPackage and reuse it by variableReplace to generate template docx again?

### ISSUE THREAD

**Issue by LinYueshan** [plutext/docx4j#322]
i want to use a WordprocessingMLPackage to generate template docx more than one time by different variables, but WordprocessingMLPackage don't have cloneable or Serializable interface, how can i do

**Comment by plutext** [comment]
https://github.com/plutext/docx4j/blob/master/src/main/java/org/docx4j/openpackaging/packages/OpcPackage.java#L899
