### ISSUE TITLE
TOC updation failed. org.docx4j.toc.TocException: Error in toc web service at https://converter-eval.plutext.com:443/v1/00000000-0000-0000-0000-000000000000/convert

### ISSUE THREAD

**Issue by munish-dhiman** [plutext/docx4j#324]
I am using 6.0.1 version of docx4j to update the `ToC table of content`. While updating `ToC`, it requesting the `PageNumberMap` from an endpoint `https://converter-eval.plutext.com:443`. The endpoint sometimes throw exception with Http Status`500` or `413`

`500` - > 

>   HTTP response: 500 Internal Server Error
   | 	at org.docx4j.toc.TocGenerator.getPageNumbersMapViaService(TocGenerator.java:711) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.getPageNumbersMap(TocGenerator.java:663) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.populateToc(TocGenerator.java:438) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:342) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:561) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:509) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:489) ~[docx4j-6.0.1.jar!/:na]

`413`-> 

> 	org.docx4j.toc.TocException: Error in toc web service at https://converter-eval.plutext.com:443/v1/00000000-0000-0000-0000-000000000000/convert
   |  HTTP response: 413 Request Entity Too Large
   | 	at org.docx4j.toc.TocGenerator.getPageNumbersMapViaService(TocGenerator.java:711) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.getPageNumbersMap(TocGenerator.java:663) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.populateToc(TocGenerator.java:438) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:342) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:561) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:509) ~[docx4j-6.0.1.jar!/:na]
   | 	at org.docx4j.toc.TocGenerator.updateToc(TocGenerator.java:489) ~[docx4j-6.0.1.jar!/:na]

My code snippet to update the `ToC` is 
> private static void generateTOC(Path document) {
        try {
            WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(document.toFile());
            TocGenerator tocGenerator = new TocGenerator(wordMLPackage);
            tocGenerator.updateToc(false); // true --> skip page numbering
            wordMLPackage.save(document.toFile());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

**Comment by plutext** [comment]
You probably have broken bookmarks in your docx.  For now, you can check/remediate using https://github.com/plutext/docx4j/blob/master/src/samples/docx4j/org/docx4j/samples/BookmarksDuplicateCheck.java

**Comment by plutext** [comment]
https://converter-eval.plutext.com is now running 2.2-5 which handles broken bookmarks more gracefully

Please install your own instance, converter-eval is only really there to make it easy for you to see whether the PDF Converter solution might be for you.
