### ISSUE TITLE
Nil table borders aren't returned in effective table style.

### ISSUE THREAD

**Issue by xsbkoconnor** [plutext/docx4j#327]
I am trying to get the effective table properties for a table through the use of PropertyResolver.getEffectiveTableStyle(). I noticed if a table has a style and has a table border value of NIL, the NIL doesn't take precedence in the effective properties.

I tracked down the issue to the following code in StyleUtil. If the source properties have a NIL border then it's not copied to the destination border. Is this expected behavior or am I using the wrong approach for getting a table's effective properties?

```
private static STBorder apply(STBorder source, STBorder destination) {
    return ((source == null) || STBorder.NIL.equals(source) ? destination : source);
}
```

**Comment by plutext** [comment]
I agree, see now https://github.com/plutext/docx4j/commit/6edba2ea20c780012cd2644477642b1414818d50
