### ISSUE TITLE
Corrupt numbering.xml after opening and saving a docx file in 6.0.1

### ISSUE THREAD

**Issue by andreasvef** [plutext/docx4j#330]
We use docx4j to replace variables in a docx file. This worked perfectly with docx4j 3.2.2, but after upgrading to 6.0.1 the numbering.xml of the docx file is corrupt when opening with MS-Word 2010. There is no further  information. We can reproduce it with the following code:
	final WordprocessingMLPackage document = Docx4J.load( new File( "original.docx" ));
        VariablePrepare.prepare( document );
	document.save( new File( "saved.docx" ), Docx4J.FLAG_SAVE_ZIP_FILE );
The output is correct without the call to prepare, but it seems that the content is not touched at all in this case. See attached zip for example:
TestDOCX4J.java: our simple test
original.docx: Original docx file
correct-3.2.2.docx: Correct output file from 3.2.2
wrong-6.0.1.docx; Corrupt output file from 6.0.1
without-prepare-6.0.1.docx: Correct output from 6.0.1 without calling pepare.
The numbering*.xml were extracted from the docx files and formatted with notepad++.

Probably the problem is around the lines 3038-3961 in numbering-wrong-6.0.1.xml. When I remove the tags with w14 namespace prefix manually the docx file can be opened without problems and the numbering is correct.

[VariablePrepareIssue.zip](https://github.com/plutext/docx4j/files/2588698/VariablePrepareIssue.zip)

**Comment by plutext** [comment]
Could you please try with https://www.docx4java.org/docx4j/docx4j-nightly-20181115.jar

**Comment by andreasvef** [comment]
Same problem with the nightly build

**Comment by plutext** [comment]
I see @mc:Ignorable="w14 wp14" is dropped in numbering.xml.  Will investigate asap and fix in docx4j 6.1.0

**Comment by plutext** [comment]
Now fixed; fix is present in https://docx4java.org/docx4j/docx4j-nightly-20181124.jar
