### ISSUE TITLE
RI mapper in the NamespacePrefixMapperUtils#getPrefixMapperRelationshipsPart

### ISSUE THREAD

**Issue by andreysubbotin** [plutext/docx4j#333]
If system uses Java 9/10, then `NamespacePrefixMapperUtils#getPrefixMapperRelationshipsPart` returns `tryUsingRI(m)`  mapper. 
I think it necessary to use `tryRIforRelationshipsPart`.

With `tryUsingRI(m)`  mapper relationships generates with namespace. LibreOffice unable to open docx with namespaces in the relationships. 
XML relationships sample: 

```
<rel:Relationships xmlns:rel="http://schemas.openxmlformats.org/package/2006/relationships"><rel:Relationship Target="styles.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Id="rId1"></rel:Relationship>
```

With docx4j 3.3.6 relationships are generated without namespace:

```
<Relationships xmlns:rel="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="styles.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Id="rId1"></rel:Relationship>
```

**Comment by plutext** [comment]
Thanks for this.  You are correct to suggest tryRIforRelationshipsPart :-)
Fix will be in 6.1.0
