### ISSUE TITLE
JPMS: Compilation fails when using docx4j as automatic module

### ISSUE THREAD

**Issue by fireandfuel** [plutext/docx4j#337]
I'm using the Java Platform Module System (JPMS) with docx4j .
I have the issue when that Java modules don't compile when requiring docx4j as automatic module. 

There are various error message from javac like:
`error: module [module-name] reads package org.apache.xml.serializer from both docx4j and serializer`

I inspected both artifacts and found out that the package org.apache.xml.serializer exists in both artifacts which JPMS threat as automatic modules. serializer is a transitive dependency of docx4j by xalan.

tested with:
OpenJDK 11.0.1

build system:
gradle 4.8.1

tested versions of docx4j:
3.3.7, 6.0.1 and 6.1.0

**Comment by plutext** [comment]
Thanks for this, I've started looking into it.  I'll be able to make a module-info.java for docx4j, but right now some of its dependencies are still automatic modules, so it may be a while before that part is stable.

There are some complexities around NamespacePrefixMapper to think through (as JAXB shipped in the Oracle JDK <=10, JAXB RI, and MOXy all have their own interface).

**Comment by plutext** [comment]
You can follow along at https://github.com/plutext/docx4j/tree/docx4j_11_0_0  (its not quite ready for prime time yet).

The Xalan issue you refer to is addressed by repackaging xalan:  https://github.com/plutext/docx4j/blob/docx4j_11_0_0/docx4j-core/src/main/java/module-info.java#L36

We have docx4j_xalan_serializer and docx4j_xalan_interpretive; these come from https://github.com/plutext/xalan-j/tree/Plutext_Java11_Repackaged_Docx4j

**Comment by plutext** [comment]
JPMS ready docx4j is now available; please see https://www.docx4java.org/forums/announces/docx4j-11-1-0-released-for-java-11-t2817.html
