### ISSUE TITLE
Unexpected parent: org.docx4j.vml.CTTextbox

### ISSUE THREAD

**Issue by oisco** [plutext/docx4j#346]
When converting a file (with advanced formatting) of type docx  to pdf the following exception is thrown:

org.docx4j.openpackaging.exceptions.Docx4JException: Unexpected parent: org.docx4j.vml.CTTextbox

Below is an example of the code which I'm using to convert to PDF and the exception is thrown at `updater.update(true)`.

` InputStream docStream = new ByteArrayInputStream(physicalData);
  WordprocessingMLPackage wordprocessingMLPackage = WordprocessingMLPackage.load(docStream);
  docStream.close();
  FieldUpdater updater = new FieldUpdater(wordprocessingMLPackage);
  updater.update(true)`

I am using version 3.3.1 but this issue is also reproducible on the latest version. I have attached a basic example of a file which I'm using to test this.

[advancedFormattingDoc.docx](https://github.com/plutext/docx4j/files/2864423/advancedFormattingDoc.docx)

**Comment by plutext** [comment]
Fix is in docx4j 6.1.2, which has now been released.

**Comment by oisco** [comment]
Works great, thanks a lot!
