### ISSUE TITLE
issue caused by using docx4j with dubbo

### ISSUE THREAD

**Issue by zidekuls** [plutext/docx4j#347]
Hi! I use docx4j to convert docx to pdf in my project, and my project use dubbo and docker.When i make test on windows,  docx4j runs well and takes about 14 seconds. But on linux where docx4j in a docker and the docker deployed by rancher. The convertion from docx to pdf takes so long time that even no response. The docx4j's log doesn't continue and dubbo's heart(heart test? sorry i can't express correctively) log append to previous log.I can't find the problem's crux. Please help me.

**Comment by plutext** [comment]
Sounds like you need to configure docker to expose the port.  You might also want to open a bash shell in your docker container to check things out:  https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell
