### ISSUE TITLE
javax.xml.bind.UnmarshalException when i load docx

### ISSUE THREAD

**Issue by hejuting** [plutext/docx4j#349]
It throws an UnmarshalException when i try to load a docx document.

The error log is as follows
![image](https://user-images.githubusercontent.com/16507695/53788084-b56e7680-3f5b-11e9-84b1-ed9ed71a5fb9.png)

The docx document is as follows
[00法學知識與英文測驗題庫03.docx](https://github.com/plutext/docx4j/files/2929746/00.03.docx)

**Comment by plutext** [comment]
That is not a docx file.  If you open it in a text editor, you will see it is HTML.

**Comment by hejuting** [comment]
You are right.thanks a lot
