### ISSUE TITLE
Encoding bug in MainDocumentPartFilterOuputStream

### ISSUE THREAD

**Issue by ChilamYan** [plutext/docx4j#357]
Hi, 
I have a problem when I  save the xml word save to docx use "WordprocessingMLPackage.save". My run-time encoding is GBK and xml encoding is UTF-8, after save, it cannot be open because the encoding not correct. I think the problem is in the file MainDocumentPartFilterOuputStream, I found three place invoking the method getBytes(), it will get the Bytes by run-time encoding not use UTF-8, after I change the code getBytes() to getBytes("UTF-8"), the file can open after save. please help to fix this problem, thanks.

**Comment by plutext** [comment]
Thank you, fixed by https://github.com/plutext/docx4j/commit/69d9303d39a48a1f3f6da7bcc760155ff2cc2b63
Will be in 8.1.1

**Comment by plutext** [comment]
8.1.1 is released: https://www.docx4java.org/forums/announces/docx4j-8-1-1-released-t2823.html
