### ISSUE TITLE
Embedded Font: How To

### ISSUE THREAD

**Issue by vbaidak** [plutext/docx4j#360]
Hi!

Thanks for the great library API!

I tried searching any help on the topic and even tried Docx4j Word Plugin (which works great indeed and saves much time), but I could find anything.

So, the question is do we have any tutorial (step-by-step) on how to embed custom font?
Say, we have an **Open Sans** font, which we want to embed and print simple **Hello, world!**

Could you please share the Java *missing part* code sample?

```java
WordprocessingMLPackage wordPackage = WordprocessingMLPackage.createPackage()

// the missing part - ???

wordPackage.save(new File("hello.docx"))
```

Thanks!

**Comment by plutext** [comment]
8.1.1 contains https://github.com/plutext/docx4j/commit/8c2de9022fc2e988075c1df100c8bf1797b4560c

So you can do something like 

```
TrueTypeFontPart ttfPart = new TrueTypeFontPart();
fontTablePart.addTargetPart(ttfPart);
```

then you'll need to add suitable content to the font table part.  Unzip a docx with an embedded font to see.

**Comment by vbaidak** [comment]
Thanks for quick response, @plutext 
I'll try it
