### ISSUE TITLE
How to create a WebExtensionPart programmatically? 

### ISSUE THREAD

**Issue by macGYves** [plutext/docx4j#364]
Hi, 

I would like to populate a WebExtensionPart with some properties and add that part to the package. 
Though, I cannot find a way to add properties to the CTOsfWebExtensionPropertyBag. 

This is what I've got so far: 
`
WordprocessingMLPackage doc = Docx4J.load(docxFile);

WebExtensionPart webExtensionPart = new WebExtensionPart(new PartName("/word/webextensions/webextension.xml"));

CTOsfWebExtension ctOsfWebExtension = new CTOsfWebExtension();
        
CTOsfWebExtensionPropertyBag bag = new CTOsfWebExtensionPropertyBag();

CTOsfWebExtensionProperty prop = new CTOsfWebExtensionProperty();
prop.setName("name");
prop.setValue("mrx");

        // bag.setProperty(prop); <-- no setter for properties available
        
ctOsfWebExtension.setProperties(bag);
webExtensionPart.setContents(ctOsfWebExtension);
doc.addTargetPath(webExtensionPart);
`

**Comment by plutext** [comment]
CTOsfWebExtensionPropertyBag contains:

```
    public List<CTOsfWebExtensionProperty> getProperty() {
        if (property == null) {
            property = new ArrayList<CTOsfWebExtensionProperty>();
        }
        return this.property;
    }
```

so use `bag.getProperty().add(prop)`

**Comment by macGYves** [comment]
Thank you!
