### ISSUE TITLE
How Do I remove the watermark on pdf file after converting docx to pdf

### ISSUE THREAD

**Issue by FlowerDance1** [plutext/docx4j#366]

**Comment by FlowerDance1** [comment]
Someone Help Me Please!It's very urgent!!!

**Comment by plutext** [comment]
You'd need to buy a license; see https://converter-eval.plutext.com/downloads/Plutext_PDF_Converter_Pricing_201710.pdf

**Comment by FlowerDance1** [comment]
Ok,Thanks!I'll talk it through with our project leader.




------------------ 原始邮件 ------------------
发件人: "Jason Harrop"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 下午4:32
收件人: "plutext/docx4j"<docx4j@noreply.github.com>;
抄送: "Up"<1214025698@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [plutext/docx4j] How Do I remove the watermark on pdf file afterconverting docx to pdf (#366)




You'd need to buy a license; see https://converter-eval.plutext.com/downloads/Plutext_PDF_Converter_Pricing_201710.pdf
