### ISSUE TITLE
Cheat sheet links in README are dead

### ISSUE THREAD

**Issue by yholkamp** [plutext/docx4j#372]
While I'm unsure if the link to https://www.docx4java.org/blog/2013/05/docx4j-in-a-single-page/ would still be relevant for the latest versions of docx4j, the links are dead. Could these cheat sheets be re-uploaded if they're still relevant?

**Comment by sndrr** [comment]
The correct links are for version 8.0.0: [pdf](https://www.docx4java.org/docx4j/plutext-docx4j_on_a_page-v800.pdf) and [png](https://www.docx4java.org/docx4j/plutext-docx4j_on_a_page-v800.png). Note that you can find them in the [doc4j directory](https://www.docx4java.org/docx4j), which is world-browsable.
