### ISSUE TITLE
org.docx4j.model.datastorage.BindingTraverserXSLT not functioning properly, when debug logging is disabled

### ISSUE THREAD

**Issue by mv-coder** [plutext/docx4j#374]
It appears that the xpathGenerateRuns() and convertXHTML() are not functioning properly, when debug level logging is disabled.

**Comment by plutext** [comment]
Are you able to provide an example where the results differ?  thanks

**Comment by mv-coder** [comment]
This test case works, when the log level is set to debug, but fails, when set to error or warn.

`import static org.junit.Assert.*;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.docx4j.Docx4J;
import org.docx4j.XmlUtils;
import org.docx4j.openpackaging.exceptions.Docx4JException;
import org.docx4j.openpackaging.packages.WordprocessingMLPackage;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class TestCase {
	
	@Test
	public void testDataMap() throws FileNotFoundException, IOException, Docx4JException {
		final Map<String,String> dataMap = new HashMap<>();
		dataMap.put("name", "Goofy");
		dataMap.put("color", "purple</color>");
		dataMap.put("number", "1");
		final ClassLoader classLoader = getClass().getClassLoader();
		final String filename = "testfiles/content-control-test.docx";
		final File file = new File(classLoader.getResource(filename).getPath());
		try(final InputStream in = new FileInputStream(file); OutputStream out = new FileOutputStream("filled-content-control.docx")) {
			WordprocessingMLPackage wordMLPackage =  Docx4J.load(in);
			Docx4J.bind(wordMLPackage, mapToXmlString(dataMap), Docx4J.FLAG_BIND_INSERT_XML | Docx4J.FLAG_BIND_BIND_XML);
			Docx4J.save(wordMLPackage, out);
			final String xml = getWordDocumentXmlAsString(wordMLPackage);
			assertTrue(xml.contains("<w:t>purple&lt;/color"));
		}
		
	}

	/*
	 * For logging, or whatever
	 */
	private String getWordDocumentXmlAsString(final WordprocessingMLPackage doc) {
		return XmlUtils.marshaltoString(doc.getMainDocumentPart().getJaxbElement(), true, true);
	}
	
	private String mapToXmlString(final Map<String, String> map) {
		final StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append("<data>\n");
		map.forEach((k,v) -> stringBuilder.append("<")
				.append(k)
				.append("><![CDATA[")
				.append(v)
				.append("]]></")
				.append(k)
				.append(">\n"));
		stringBuilder.append("</data>");
		return stringBuilder.toString();
	}
}`

[content-control-test.docx](https://github.com/plutext/docx4j/files/3994188/content-control-test.docx)

**Comment by mv-coder** [comment]
@plutext This issue is fixed through some other changes you made in the area, where this problem existed.
