### ISSUE TITLE
Is it possible to count the data size of each page of a word document?

### ISSUE THREAD

**Issue by gyckey** [plutext/docx4j#376]
Is it possible to count the data size of each page of a word document?

For example: how much is the data on the first page?

**Comment by plutext** [comment]
To do this you'd need to know where the "pages" start and end, and for that you need a page layout model.  Word writes a "last rendered page break" tag, which may be enough for your purposes.  Then there's the question of what you mean by "data size": count of characters on the document surface, plus image bytes?   Or table cells?
