### ISSUE TITLE
w16

### ISSUE THREAD

**Issue by stewmorg** [plutext/docx4j#381]
I'm seeing an increasing number of word files being generated with xml namespaces that contain:

xmlns:w16cex="http://schemas.microsoft.com/office/word/2018/wordml/cex"
            xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid"
            xmlns:w16="http://schemas.microsoft.com/office/word/2018/wordml"

It would seem that when these files are read into Docx4j with their content read (e.g. by calling getContent() on the MainDocumentPart), the resulting saved docx file is no longer able to be opened by Word without it being "recovered" or then again by docx4j.

Having searched the repo, I don't see any reference to w16 and was wondering if there was a known issue around w16 in the namespaces?

**Comment by plutext** [comment]
Could you please attach an input docx which uses w16 and w16cex?

**Comment by plutext** [comment]
Thanks for this.  Fixed by https://github.com/plutext/docx4j/commit/9b0731d8a2fabe75c12d013dd5f749bdcdad0670
Will be in a new release over the next week or so.

**Comment by MykolaMyndyk** [comment]
Hi
Could this issue be also fixed in 6.1.2?
Thanks

**Comment by plutext** [comment]
Any reason you can't upgrade to 8.1.5 or later?

**Comment by varetalks** [comment]
I have the same issue with "w16sdtdh" and don't see any reference to it in the repo either.
Could the mapping for xmlns:w16sdtdh="http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash" be added too?

**Comment by plutext** [comment]
Could you please attach a docx containing that namespace and/or instructions for creating such a docx?  What version of Word are you using, on what platform?

**Comment by jdkcn** [comment]
> I have the same issue with "w16sdtdh" and don't see any reference to it in the repo either.
> Could the mapping for xmlns:w16sdtdh="http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash" be added too?

The same problem.

**Comment by varetalks** [comment]
I am using Word Version 2103 (Build 13901.20336) on Windows 10. I have attached a zip with two files that contain the w16sdtdh namespace: a .dotx file and a .docx file



[Files_with_namespace.zip](https://github.com/plutext/docx4j/files/6286304/Files_with_namespace.zip)

**Comment by jingglang** [comment]
I got error

`no mapping for prefix w16sdtdh`

The fix by @jdkcn fixed my problem.

**Comment by plutext** [comment]
This will be fixed in a new release later this week.

**Comment by tnodev** [comment]
+1

**Comment by plutext** [comment]
http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash is new in [MS-DOCX] v15.0 of 22 March

**Comment by plutext** [comment]
Fixed in 8.2.9
