### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by telemmaite** [plutext/docx4j#394]
Hello thank you for **your wonderful library**, I wonder is there a docker image which is up to date?

I plan to use it as a `service` hitting a running docker container which listens on a port and pass my document via curl post.
I would be also fine if there is a tutorial how to build the image myself.

**Comment by jasonisgraham** [comment]
Hey there @telemmaite ... I was bored and slapped in docker and a lil web server written in Clojure here: https://github.com/jasonisgraham/docx4j/tree/dockerize  

Goes without saying, but this is *not* production ready.

**Comment by telemmaite** [comment]
Thanks a lot, getting started was all that I need.
