### ISSUE TITLE
Unable to get font/style from Word doc 

### ISSUE THREAD

**Issue by viveknani98** [plutext/docx4j#412]
I am trying to get the fonts and styles from a Word doc. Below is the code that I tried.

public class Docx4jexample {
	public static void main(String[] args) {
		try {
			WordprocessingMLPackage wordMLPackage = Docx4J.load(new java.io.File("C:\\Users\\vivek.r1\\Desktop\\templateMDDT.docx"));
			MainDocumentPart documentPart = wordMLPackage.getMainDocumentPart();
			StyleDefinitionsPart sdp = wordMLPackage.getMainDocumentPart().getStyleDefinitionsPart(true);
			for (Style s : sdp.getContents().getStyle()) {
					RPr rPr = s.getRPr();
					System.out.println(rPr.getSz());
			}
		}catch (Docx4JException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
[templateMDDT.docx](https://github.com/plutext/docx4j/files/5075990/templateMDDT.docx)

**Comment by plutext** [comment]
What happened, and what were you expecting to happen?

**Comment by viveknani98** [comment]
In the templateMDDT.docx, I had 6 lines and each line had different formatting like
line 1 - bold, font size - 28
line 3 - bold font size - 20
line 5 - bold, font size - 14

I want to read the font size and formatting into Java(get those as variables or print them on console), the java code which I shared above is returning Null pointer exception(tried to print the variable rPr, it is returning Null).
