### ISSUE TITLE
Chinese cannot set font

### ISSUE THREAD

**Issue by zhangchao6960** [plutext/docx4j#418]
If the value is Chinese, it cannot be set font.
result font is Calibri.

docx4j version : 6.1.2 
jdk : 1.8

test code 

        String value = "English"; // Chinese value is "中文"
        String fonts = "simsun";
        //init
        P p = factory.createP();
        Text text = factory.createText();
        text.setValue(value);
        R run = factory.createR();
        run.getContent().add(text);
        p.getContent().add(run);
        //set ppr rpr
        PPr ppr = factory.createPPr();
        p.setPPr(ppr);
        RPr runProperties = factory.createRPr();
        run.setRPr(runProperties);
        //set font
        RFonts rFonts = factory.createRFonts();
        rFonts.setAscii(fonts);
        runProperties.setRFonts(rFonts);
        //add text
        wordPackage.getMainDocumentPart().getContent().add(p);

**Comment by Y175** [comment]
have solution？

**Comment by plutext** [comment]
rfonts.setHint(org.docx4j.wml.STHint.EAST_ASIA);
                        rfonts.setAscii( "MS Mincho"); 
                        rfonts.setHAnsi( "MS Mincho"); 
                        rfonts.setEastAsia( "MS Mincho"); 
                        rfonts.setCs( "MS Mincho");
