### ISSUE TITLE
Cellvalue can only get numeric value, cannot get text. Do you have test?

### ISSUE THREAD

**Issue by z503951608** [plutext/docx4j#429]
SpreadsheetMLPackage xlsxPkg = SpreadsheetMLPackage.load(new java.io.File(inputfilepath));		
				
		WorkbookPart workbookPart = xlsxPkg.getWorkbookPart();
		WorksheetPart sheet = workbookPart.getWorksheet(0);
				
                Worksheet ws = sheet.getContents();
		SheetData data = ws.getSheetData();
		
		for (Row r : data.getRow() ) {
			System.out.println("row " + r.getR() );			
			
			for (Cell c : r.getC() ) {
				
				String cellValue = c.getV();
}
}

Cellvalue can only get numeric value, cannot get text. Do you have test?

**Comment by plutext** [comment]
See https://github.com/plutext/docx4j/blob/master/docx4j-samples-xlsx4j/src/main/java/org/xlsx4j/samples/CellContentExtractor.java

Please don't use the issue tracker unless it is a bug.  Instead, use StackOverflow, the docx4j forums, or the "Discussions" tab above.
