### ISSUE TITLE
Add mappings for w16 and w16cex into 6.1.2 version

### ISSUE THREAD

**Issue by MykolaMyndyk** [plutext/docx4j#433]
Hi,

Currently, we are using docx4j version 6.1.2, and we faced the same problem as in https://github.com/plutext/docx4j/issues/381
I see that issue was fixed in 8.1 - 8.2 version - https://github.com/plutext/docx4j/commit/9b0731d8a2fabe75c12d013dd5f749bdcdad0670

We tried to migrate to 8.x.x versions but unfortunately, those versions are failing our builds, and the only version that we are able to work with is 6.1.2.
Could you also add this fix there in 6.1.2 version.

Thank you in advance

**Comment by MykolaMyndyk** [comment]
Hi @plutext have you had a chance to take a look at this issue?
Thanks

**Comment by plutext** [comment]
Whilst we do backports for customers where it makes sense to do so, here it would be better to understand why you can't use a current release.

**Comment by plutext** [comment]
See also https://github.com/plutext/docx4j/issues/381
