### ISSUE TITLE
Saving as FlatXML trims Namespaces too aggressively

### ISSUE THREAD

**Issue by jhrtl** [plutext/docx4j#444]
# The problem
If saving a document to flatxml, the created xml file cannot be opened with Word complaining about xml schema without naming details. 
This seemingly does not affect all documents, but it seems nearly any document containing a textbox does.

# Reproduction
I attached a small sample project opening a Textbox docx, re-saving it as a flat xml which does not open for me (Word 2019).
[Sample project.zip](https://github.com/plutext/docx4j/files/6334847/Sample.project.zip)

# Analysis
The problem seems to be about namespaces. Aligning the contents of a flatxml created by word itself with the docx4j-flatxml, there isn't that much difference. Main difference is that docx4j seems to trim namespaces per xml part very and probably too aggressive. Copying over the full xmlns declarations from the word-created flatxml resolves the issue. 

I attached Original Output as from Reproduction above, a version saved with Word, a version corrected by copying over Word-namespaces and some intermediate file showing that while copying namespaces, Word somewhen is able to pin down the error the the one xml part not having been corrected yet. All xml are pretty-print for easy comparison.
[xmls.zip](https://github.com/plutext/docx4j/files/6334849/xmls.zip)

**Comment by plutext** [comment]
On a preliminary look, it looks like the Canonicalizer is dropping the namespace declarations for those prefixes which are present only in @mc:Ignorable, for example mc:Ignorable="w14 w15 w16se w16cid wp14".  Word complains unless these prefixes are declared.

The intent is that the Canonicalizer keep these namespace declarations, so we'll need to see why they are being dropped.

**Comment by mc** [comment]
Do you want my opinion? :-)

**Comment by jhrtl** [comment]
Made my day. Unexpected chat messages while referring to xml attributes :laughing:

**Comment by plutext** [comment]
Turns out that the Canonicalizer is working fine.  The problem occurs later.  

We have a JAXB representation for the package object, and when this is marshalled, the ignorable namespaces are being collected at the top:

```
<pkg:package
	xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage"
	xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing"
	xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex"
	xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"
	xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml"
	xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid">
```

instead of being duplicated lower in the tree in each pkg:part object, as Word expects.

In the past, we didn't need to worry about this, but now, evidently, we do.

I haven't investigated whether this is a result of changes in JAXB, or simply because the mc:ignorable mechanism is now used in multiple parts.

Need to think about how to handle it.

**Comment by jhrtl** [comment]
Thanks for your efforts :). The fix looks rather elaborate.

I pulled the repo, build and ran my unit tests on it. From what i see the new algorithm will fail on some cases. It will produce a crash and a corrupt document.

```java
org.docx4j.openpackaging.exceptions.Docx4JException: Couldn't marshall Flat OPC Package
	at org.docx4j.convert.out.flatOpcXml.FlatOpcXmlCreator.marshal(FlatOpcXmlCreator.java:231) ~[docx4j-core-8.2.10-SNAPSHOT.jar:?]
	at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:739) ~[docx4j-core-8.2.10-SNAPSHOT.jar:?]
	at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:684) ~[docx4j-core-8.2.10-SNAPSHOT.jar:?]
	at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:667) ~[docx4j-core-8.2.10-SNAPSHOT.jar:?]
	at bugrepro.Reproduce.openDocxSaveAsFlatXML(Reproduce.java:24) [classes/:?]
	at bugrepro.Reproduce.main(Reproduce.java:16) [classes/:?]
Caused by: javax.xml.bind.MarshalException
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:301) ~[jaxb-runtime-2.3.2.jar:2.3.2]
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:226) ~[jaxb-runtime-2.3.2.jar:2.3.2]
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:95) ~[?:1.8.0_281]
	at org.docx4j.convert.out.flatOpcXml.FlatOpcXmlCreator.marshal(FlatOpcXmlCreator.java:216) ~[docx4j-core-8.2.10-SNAPSHOT.jar:?]
	... 5 more
Caused by: com.sun.istack.SAXException2: unable to marshal type "org.docx4j.xmlPackage.Part" as an element because it is missing an @XmlRootElement annotation
	at com.sun.xml.bind.v2.runtime.XMLSerializer.reportError(XMLSerializer.java:219) ~[jaxb-runtime-2.3.2.jar:2.3.2]
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:308) ~[jaxb-runtime-2.3.2.jar:2.3.2]
	at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:464) ~[jaxb-runtime-2.3.2.jar:2.3.2]
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:298) ~[jaxb-runtime-2.3.2.jar:2.3.2]
	at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:226) ~[jaxb-runtime-2.3.2.jar:2.3.2]
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:95) ~[?:1.8.0_281]
	at org.docx4j.convert.out.flatOpcXml.FlatOpcXmlCreator.marshal(FlatOpcXmlCreator.java:216) ~[docx4j-core-8.2.10-SNAPSHOT.jar:?]
	... 5 more
```

It seems all my tests failing like this got an image somewhere in the document. I built some small sample documents and put them into a reproduction maven project.
[444-continued.zip](https://github.com/plutext/docx4j/files/6364504/444-continued.zip)

**Comment by plutext** [comment]
https://github.com/plutext/docx4j/commit/2359c59fb5024c33c7e9bb86240d72efd3ea2feb should fix that

**Comment by jhrtl** [comment]
hmm ... unfortunately only at first glance :/ -> It will no longer crash.

This way the previously crashing documents now end up with additional xml Headers inside the xml document itself. That's against xml specification, so no xml parser, let alone Word, will tolerate that. 
```xml
	<pkg:part pkg:name="/word/media/image1.jpeg" pkg:contentType="image/jpeg">
		<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
		<pkg:part xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage" pkg:name="/word/media/image1.jpeg" pkg:contentType="image/jpeg" pkg:compression="store">
```
The reproduction project from above is still valid for this issue.

**Comment by plutext** [comment]
Sure, those extra declarations are a problem :-)  Please try
https://github.com/plutext/docx4j/commit/4bbb60acad5387e5faae446f5faee7e818f7cee0

I haven't tried your repro yet, but will in the morning if this doesn't fix
it.

**Comment by jhrtl** [comment]
This resolves the multiple xml declarations problem ... but unfortunately my unit-tests still indicate problems. 
Some parts (images, again...) now end up with duplicated part structures.

Instead of 
```xml
<pkg:part xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage" pkg:name="/word/media/image1.jpeg" pkg:contentType="image/jpeg" pkg:compression="store">
	<pkg:binaryData>...</pkg:binaryData>
</pkg:part>
```

the result reads
```xml
<pkg:part pkg:name="/word/media/image1.jpeg" pkg:contentType="image/jpeg">
	<pkg:part xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage" pkg:name="/word/media/image1.jpeg" pkg:contentType="image/jpeg" pkg:compression="store">
		<pkg:binaryData>...</pkg:binaryData>
	</pkg:part>
</pkg:part>
```

which does Word no good. My reproduction sample 444-continued is still suited to show this.

But for now please enjoy the weekend you already started extremely late. Let's continue on monday.

**Comment by plutext** [comment]
I can't repro this, using a simple docx containing just a single png or jpg.  Could you please attach a docx I can try?

**Comment by jhrtl** [comment]
Executing reproduction 444-continued will show this. Insde src\main\resources you will also find 4 docx files. The "failing" ones will produce such results if re-saved as flatxml

**Comment by plutext** [comment]
OK, should be good with https://github.com/plutext/docx4j/commit/c7afe9962c6ec01ef2e8a34fb1ab6baf77663d3a

**Comment by jhrtl** [comment]
After feeding this through my unit tests: Most documents will now create a valid flatxml.

However, a few still won't. In my case the ones which create (technically: import) a textbox not present before. I guess this is more about creation of something not present before, but as textboxes are deep xml constructs, i never constructed one in pure code.

I streamlined these cases to the following reproduction:
1. Define a Base document and a Textbox document
2. Load both and fetch their main document's contents
3. Append the textbox to the content of base
4. Save

At this point, things are getting interesting:
1. If saving to docx, the result is a valid document and can be opened with Word
2. If saving to flatxml, the result won't open in Word
3. If opening docx from 1) and saving *that* into flatxml, the result is valid document

I uploaded these steps as an executable maven project here: [444-continued2.zip](https://github.com/plutext/docx4j/files/6379156/444-continued2.zip)

Differences between 1 and 3 clearly locate the error: 
In 1 (the flatxml failing to open) the Textbox contains the following wps:
```xml
<wps:wsp xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape">
```
whereas in 3 (the flatxml opening correctly) wsp is declared in the namespaces of document.xml itself, leaving just
```xml
<wps:wsp>
```
at the place of usage.

It seems Word does not tolerate an inline declaration of wps. 

In case you're only interested in the xml difference: [Only files.zip](https://github.com/plutext/docx4j/files/6379162/Only.files.zip)

Note: I'll be unavailable for about a week, but will check eventual changes then.

**Comment by plutext** [comment]
I expect that the actual issue is that the document contains
```
	<mc:Choice Requires="wps">
```

and Word requires that such prefixes be declared.

The comment in McIgnorableNamespaceDeclarator says:
```
 * Docx4j will ensure that each namespace in mc:Ignorable is properly declared
 * (as it needs to be in order for Office to open the file), 
 * but if you add mc:Ignorable content, it is still generally up to you to set the mc:Ignorable 
 * attribute correctly.  Exceptions are DocumentSettingsPart, where docx4j
 * tries to set it correctly for you, and pptx where currently "v" is assumed.
 * 
 * Note that there is a difference between the prefixes which need to be
 * in mc:Ignorable, and the requirement to pre-declare namespaces used
 * in mc:Choice (eg Requires="wpg")
 * 
 * But since both require the namespace to be pre-declared, this mechanism is 
 * used for both. (search for getMcChoiceNamespaces)
```
 
In terms of your continued2 project, try:

```
		/**
		 * Insert textbox into base
		 */
		baseContents.addAll(textboxContents);
		// add the following
		base.getMainDocumentPart().addMcChoiceNamespace("wps");
```

**Comment by jhrtl** [comment]
At first i was rather confused as saving as .docx isn't affected ... but yes, that's the real issue and fitting workaround/solution. Thanks :)
When doing so, my tests ran correctly and produced open-able documents.

I guess .docx is more robust on this regard as it declares a wide range of namespaces regardless if they are used or not. Perhaps there are edge cases where .docx also requires to do so, but i haven't found any up to now. 
Flatxml declares minimalistic and therefore is much more prone to errors if not using this workaround to add namespaces.
