### ISSUE TITLE
Unwanted numbering appearing after variable preapre

### ISSUE THREAD

**Issue by vinujan59** [plutext/docx4j#447]
docx4j version - org.docx4j:docx4j-parent:11.2.9

Scenario - When saving a document after VariablePrepare.prepare, and converting the docx file using libreoffice to pdf, unwanted numbering is appearing in the converted pdf.

Some observations

- This does not happen for every file
- can see the unwanted numbering when opening via libre office
- opening via ms office word doesn't show this issue

Screenshot of the unwanted numbering

![image](https://user-images.githubusercontent.com/11666269/116502470-231d4f80-a8e6-11eb-9972-794b54d9b99d.png)

Looking at the `numbering.xml` file, I found that docx4j doesn't add the attribute `w15:restartNumberingAfterBreak="0"` from the original document. It seems there is an [existing issue](https://github.com/plutext/docx4j/issues/224) related to this.

Does this error scenario related to the above? or is some other causing the issue?

Please guide me in resolving this.

**Comment by plutext** [comment]
Possible bug in LibreOffice?  What version of LO are you using?  Have you tried their latest release?

**Comment by vinujan59** [comment]
I tried the above scenario with the latest [stable version](https://www.libreoffice.org/download/download/) of LibreOffice `7.0.5` and `7.0.4`. Failed. 

It could be a bug with the LibreOffice, but the original document is opening correctly but the document saved after docx4j is having the numbering issue.

**Comment by plutext** [comment]
You could compare your original docx with the output docx to see what is different (ie unzip and look at document.xml numbering.xml and possibly styles.xml)

**Comment by vinujan59** [comment]
Sure, I will make the comparison and get back to you with the differences. 

Thank you for the replies.

**Comment by plutext** [comment]
Closing after no reply for 1 month
