### ISSUE TITLE
Issue within NamespacePrefixMapperUtils - namespacePrefixMapper is null

### ISSUE THREAD

**Issue by ryno1234** [plutext/docx4j#449]
Long time .Net developer working on a Java project and despite the similarities, I am having trouble wrapping my head around how to troubleshoot something.

I have a Spring project which is running on Wildfly 12 and we use Maven to build. I just updated docx4j from 3.3.4 to 8.0.0.

When running our test suites, our docx4j-related tests run fine, when launching Wildfly, I get an exception:

```
namespacePrefixMapper is null: javax.xml.bind.JAXBException: namespacePrefixMapper is null
	at org.docx4j.jaxb.NamespacePrefixMapperUtils.setProperty(NamespacePrefixMapperUtils.java:164)
	at org.docx4j.openpackaging.contenttype.ContentTypeManager.marshal(ContentTypeManager.java:916)
	at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveContentTypes(ZipPartStore.java:265)
	at org.docx4j.openpackaging.io3.Save.save(Save.java:177)
```

I tried to set a breakpoint in `NamespacePrefixMapperUtils.getPrefixMapper()` to see when the `prefixMapper` gets set, but I get as far as hitting that code while debugging. Furthermore, the `haveTried` value equals `true` by the time I hit `getPrefixMapper()`. Somehow this function is executing without my debugger breaking on the initial run through.

All of this said, that was just my debugging effort to understand why I'm having an issue. Really, my core issue is I need to understand why docx4j works fine in my unit tests but doesn't work when I run it on Wildfly.

Bonus question: It's not clear to me what the heck the NamespacePrefixMapper does and what roll it places in reading / writing Word documents.

**Comment by ryno1234** [comment]
Regardless of why I can't hit the breakpoint and regardless of the purpose of the NamespacePrefixMapper, I DID find that my `JAXBContext` is of type `com.sun.xml.bind.v2.runtime.JAXBContextImpl`, which doesn't look like it is any of the supported types. I'm not sure where this type registration is coming from because I'm not explicitly including this jar. I'll research further, but wanted to provide a comment in the event that someone checks this before I figure out the issue.

**Comment by plutext** [comment]
Did you have docx4j 3.3.4 running under Wildfly 12?

According to http://www.mastertheboss.com/jboss-server/jboss-eap/what-is-the-difference-between-jboss-eap-wildfly-and-jboss-as Wildfly 12 is somewhere between EAP 7.1 and 7.2.  

For Wildfly config instructions, try https://www.docx4java.org/forums/jboss-f29/ or https://stackoverflow.com/questions/16204635/cannot-use-docx4j-inside-of-jboss-7/24301422

Regarding docx4j version, I'd recommend you go with v8.2.9; see https://www.docx4java.org/forums/announces/docx4j-8-2-9-released-following-word-updates-t2979.html

**Comment by ryno1234** [comment]
@plutext, Whoops. I was wrong about that. We had docx4j 3.3.1 running. We had a separate project dependency on 3.3.4 which is inconsequential in this issue.

Long story short, using the ReferenceImplementation version fixed the problem.

**Comment by plutext** [comment]
Yes, a warning from Microsoft Word when opening the document indicating that it was corrupt is the symptom, and likely cause if you've created a document in Word, then minimally manipulated it with docx4j, then find Word can't open the result.

**Comment by ryno1234** [comment]
Thanks again
