### ISSUE TITLE
export fo Chinese rPr Bold / Italic

### ISSUE THREAD

**Issue by kwan815** [plutext/docx4j#451]
I use export-fo to convert docx with Chinese characters to pdf. The file can be converted successfully but the formatting on Chinese characters were all lost. The formatting are bold, italic, justified text and character spacing.

This is the original docx file -> [test.docx](https://github.com/plutext/docx4j/files/6547515/test.docx)
This is the converted pdf by using export-fo -> [test.pdf](https://github.com/plutext/docx4j/files/6547520/test.pdf)
This is the pdf file generated by using [Save As] in MS Word for comparison -> [test (by Save As).pdf](https://github.com/plutext/docx4j/files/6547526/test.by.Save.As.pdf)

In the above test.docx, bold, italic, underline and character spacing are applied to the question. The alphanumeric characters are converted as expected, but only underline is effective to Chinese characters. For the paragraphs, only justified text and character spacing are applied, but none of it effective.

pom.xml
<pre>
&lt;dependency&gt;
	&lt;groupId&gt;org.docx4j&lt;/groupId&gt;
	&lt;artifactId&gt;docx4j-core&lt;/artifactId&gt;
	&lt;version&gt;8.2.9&lt;/version&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
	&lt;groupId&gt;org.docx4j&lt;/groupId&gt;
	&lt;artifactId&gt;docx4j-JAXB-ReferenceImpl&lt;/artifactId&gt;
	&lt;version&gt;8.2.9&lt;/version&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
	&lt;groupId&gt;org.docx4j&lt;/groupId&gt;
	&lt;artifactId&gt;docx4j-export-fo&lt;/artifactId&gt;
	&lt;version&gt;8.2.9&lt;/version&gt;
&lt;/dependency&gt;
</pre>

Java
<pre>
File inFile = new File("test.docx");
File outFile = new File(inFile.getParentFile(), inFile.getName().replace(".docx", ".pdf"));

InputStream is = new FileInputStream(inFile);
WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(is);
PdfSettings pdfSettings = new PdfSettings();

org.docx4j.convert.out.pdf.PdfConversion conversion = new org.docx4j.convert.out.pdf.viaXSLFO.Conversion(wordMLPackage);
OutputStream out = new FileOutputStream(outFile);
conversion.output(out, pdfSettings);
</pre>

I tried documents4j and it can convert docx with Chinese characters perfectly. However, the conversion machine must be a Windows with MS Office installation.

**Comment by plutext** [comment]
Restricting this issue to rPr;   see https://github.com/plutext/docx4j/issues/452 for text justification

**Comment by plutext** [comment]
[min_fonts.docx](https://github.com/plutext/docx4j/files/6550847/min_fonts.docx) is a minimal test document for the bold/italic issue

Your document uses font PMingLiU, however, there aren't "real" bold and italic forms for this font.   Instead, Microsoft Word synthesizes bold and italic forms:

https://fop-users.xmlgraphics.apache.narkive.com/tEIRB0Eg/chinese-character-in-bold
https://adobe.indesign.windows.narkive.com/WhDlTulQ/cs4-xp-pro-missing-bold-and-italic-fonts-for-pmingliu-font

A workaround would be to use a font which has real bold and italic forms.    For example, Noto has a bold typeface:   https://fonts.google.com/specimen/Noto+Sans+TC#standard-styles  (Does your sample docx contain Simplified or Traditional Chinese?)

As far as I can tell, Italics is another challenge.  People say there is no concept of italics in Chinese?  But it can be faked; see for example https://community.adobe.com/t5/indesign/bold-and-italics-in-chinese/m-p/9765151 

Following https://stackoverflow.com/questions/48039612/how-to-create-italic-bold-fonts-automatically-in-apache-fop we can try fop's "simulate-style" setting. 

What do you ultimately want to do with the PDF output?  Is it for users to read onscreen, or for printing by a publishing house?

**Comment by plutext** [comment]
simulate-style works for PMingLiU to produce bold/italic.

[min_fonts.docx.pdf](https://github.com/plutext/docx4j/files/6557628/min_fonts.docx.pdf)

The underline doesn't look so good?

**Comment by mlkui** [comment]
> simulate-style works for PMingLiU to produce bold/italic. [16c85ce](https://github.com/plutext/docx4j/commit/16c85ce726efb4330d5e47de309cb11f5c75d25f)
> 
> [min_fonts.docx.pdf](https://github.com/plutext/docx4j/files/6557628/min_fonts.docx.pdf)
> 
> The underline doesn't look so good?

Thank you. This saves my day. 
The underline is ok to use.
