### ISSUE TITLE
Support for JakartaEE 9

### ISSUE THREAD

**Issue by fireandfuel** [plutext/docx4j#458]
docx4j currently uses JakartaEE 8's `jakarta.xml.bind-api` v2.3.2 as a compile dependency and can not be used when running on JakartaEE 9's `jakarta.xml.bind-api` v3.0.0 or newer because JakartaEE 9 switched the namespace from `javax.*` to `jakarta.*`.

Forcing the user to migrate from JakartaEE 8 to JakartaEE 9 in a new version of docx4j seems to break a lot of projects which are not already migrated to JakartaEE 9. It would be better to let the user choose which version of JakartaEE they want to use. For the most cases this might be the best way to enable a smooth migration from JakartaEE 8 to JakartaEE 9.

Thus it would be nice to have a Maven artifact like hibernate did with [hibernate-core](https://search.maven.org/artifact/org.hibernate/hibernate-core) (for JakartaEE 8) and [hibernate-core-jakarta](https://search.maven.org/artifact/org.hibernate/hibernate-core-jakarta) (for JakartaEE 9) or like an additional version of docx4j which uses JakartaEE 9 instead of JakartaEE 8.

**Comment by plutext** [comment]
We do plan to support jakarta.xml.bind-api, likely in a v11.4 release.

**Comment by plutext** [comment]
See now https://github.com/plutext/docx4j/tree/VERSION_11_4_0 which is ready for early testing; you need to build it from source (mvn install).

**Comment by thetric** [comment]
Good to hear that the Jakarta EE support is on the way :) What issues are blocking the 11.4 release? This is kind a hard to track in GitHub

**Comment by plutext** [comment]
Hi, the plan is:
1. to release 8.3.3 (from master branch), 
2. then port the commits of earlier this month at https://github.com/plutext/docx4j/commits/master to the 11.4.0 branch
3. release 11.4.0

We should get to step 3 next week.

Slightly off topic but for completeness: In principle, there could also be a v8.4.0, that is, docx4j using Jakarta XML binding and compiled for Java 8, but that would be a niche need at best I think, so right now there is no plan for that.

**Comment by plutext** [comment]
v11.4.5 which uses jakarta.xml is now in Maven Central
