### ISSUE TITLE
The color of the Chinese font of word to pdf turns to black.(simulate-style )

### ISSUE THREAD

**Issue by FredWym** [plutext/docx4j#459]
It is found in docx4j 8.3.0 that after adding the bold configuration (docx4j.fonts.fop.util.FopConfigUtil.simulate-style=true), the color of the Chinese font of word to pdf turns to black. 

[https://github.com/FredWym/doc/blob/master/pr.docx](url)

**Comment by plutext** [comment]
Since this appears to be an issue in the upstream project Apache FOP, may I suggest you raise the issue there?

For their JIRA, see https://xmlgraphics.apache.org/fop/bugs.html

For their mailing lists, see https://xmlgraphics.apache.org/fop/maillist.html

If you do raise an issue in their JIRA, please include a link to it here.  thanks.

**Comment by FredWym** [comment]
thanks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plutext/docx4j"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plutext/docx4j] The color of the Chinese font of word to pdf turns to black.(simulate-style ) (#459)





 
Since this appears to be an issue in the upstream project Apache FOP, may I suggest you raise the issue there?
 
For their JIRA, see https://xmlgraphics.apache.org/fop/bugs.html
 
For their mailing lists, see https://xmlgraphics.apache.org/fop/maillist.html
 
If you do raise an issue in their JIRA, please include a link to it here.  thanks.

**Comment by plutext** [comment]
They are going to want .fo input sample, not a docx file.  For example, something like:

```
			<fo:block font-size="10.5pt" text-align="justify">
				<inline xmlns="http://www.w3.org/1999/XSL/Format"
					font-size="10.5pt">
					<inline font-family="等线">测试结果</inline>
					<inline font-family="等线">：</inline>
				</inline>
			</fo:block>
			<fo:block font-size="10.5pt" text-align="justify">
				<inline xmlns="http://www.w3.org/1999/XSL/Format"
					font-family="等线">Test Results</inline>
				<inline xmlns="http://www.w3.org/1999/XSL/Format"
					font-size="10.5pt">
					<inline font-family="等线">：</inline>
				</inline>
			</fo:block>
```

Also, you already did the work to find where things go wrong in the FOP code base, so it would be great to include that in your JIRA issue.

**Comment by plutext** [comment]
https://issues.apache.org/jira/browse/FOP-3015

**Comment by FredWym** [comment]
https://issues.apache.org/jira/browse/FOP-3015  problem solved
