### ISSUE TITLE
w16se w16cid currently aren't added thread-safe and thus tend to corrupt documents

### ISSUE THREAD

**Issue by jhrtl** [plutext/docx4j#464]
Given version 8.3.0 (MOXy), the namespaces w16se and w16cid seemingly aren't added in a thread-safe manner. Maybe it's more likely to occur on MOXy as MOXy tends to minify the namespaces more than other implementations.

I found some of my documents to randomly fail. Not by exception, but by creating a file that won't open in Word afterwards. The reason would always be the same: ``mc:Ignorable="w14 w15 w16se w16cid"`` is declared, but the corresponding ``xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex"`` are missing, compared to the "normal" execution result.

This behaviour can be reproduced by loading a "Hello world" minimal sample document, doing minimal work on contained P and re-saving it afterwards. Looping this on 4 threads concurrently will reproduce the issue within seconds. Each thread only uses its' own objects, no objects are shared.

I attached a reproduction project -> [reproduction.zip](https://github.com/plutext/docx4j/files/6735106/reproduction.zip). It saves the result as flatxml to byte[] which gets hashed by guava. As soon hashes start to differ, execution is halted and both flatxml are dumped. The difference then clearly shows the missing xmlns.
In case you are only interested in the results from my run, i also attached [results.zip](https://github.com/plutext/docx4j/files/6735098/results.zip)

**Comment by jhrtl** [comment]
Note: This isn't a flatxml-issue. I discovered it on .docx. flatxml is just very convenient as the lack of metadata creates identical results and because it's very easy to diff.

**Comment by plutext** [comment]
Thanks for this @jhrtl

**Comment by jhrtl** [comment]
I have to thank you
