### ISSUE TITLE
org.docx4j.vml.CTLine is distorted on saving document

### ISSUE THREAD

**Issue by jhrtl** [plutext/docx4j#469]
# Description
When loading a document containing a line (more specifically org.docx4j.vml.CTLine) and re-saving this document after looking into the relevant Part (causing unmarshalling), the appearance of the line(s) will be distorted. For me, most of the time, it will shift towards the center of the document. Though while analyzing this phenomenon, it seems other distortions like change in length are possible as well.

This is a silent error. No error is logged. One has to check the document visually.

|Original document|Opened and re-saved with docx4j|
|-|-|
|![grafik](https://user-images.githubusercontent.com/66481421/127666459-25f916f1-7ba1-4b56-9212-fca496d00995.png)|![grafik](https://user-images.githubusercontent.com/66481421/127666543-64600325-6f49-4215-81ec-7426b3a6bd48.png)|

# Analysis 
Analysing this problem i found the reason to be the ordering of attributes of v:line. 
<table><tr><th>Original document and order which is used by Word</th><th>Order after re-save with docx4j</th></tr><tr><td>

```xml
<w:pict>
	<v:line 
		id="_x0000_s2049" 
		style="position:absolute;left:0;text-align:left;z-index:251656704;mso-position-horizontal-relative:text;mso-position-vertical-relative:page" 
		from="-56.7pt,586.85pt" 
		to="-42.55pt,586.85pt" 
		o:allowoverlap="f">
		<w10:wrap anchory="page"/>
		<w10:anchorlock/>
	</v:line>
</w:pict>
```

</td><td>

```xml
<w:pict>
	<v:line 
		from="-56.7pt,586.85pt" 
		to="-42.55pt,586.85pt" 
		style="position:absolute;left:0;text-align:left;z-index:251656704;mso-position-horizontal-relative:text;mso-position-vertical-relative:page" 
		id="_x0000_s2049" 
		o:allowoverlap="f" 
		xmlns:v="urn:schemas-microsoft-com:vml" xmlns:xvml="urn:schemas-microsoft-com:office:excel" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:pvml="urn:schemas-microsoft-com:office:powerpoint">
		<w10:wrap anchory="page"/>
		<w10:anchorlock/>
	</v:line>
</w:pict>
```

</td></tr></table>

Re-Ordering the attributes to id > style > from > to > o as Word does fixes the problem. Perhaps it's about the style attribute also containing positioning information.

I'm also wondering why docx4j inserts excel and powerpoint namespaces, but this seemingly does not cause problems.

# Reproduction
- Sample input document: [Input.docx](https://github.com/plutext/docx4j/files/6908311/Input.docx)
- Sample output document: [Re-Saved.docx](https://github.com/plutext/docx4j/files/6908310/Re-Saved.docx)
- Reproduction maven project: [Project.zip](https://github.com/plutext/docx4j/files/6908347/Project.zip)

**Comment by plutext** [comment]
This is extraordinary, since in XML, attribute order is not supposed to be significant.

Evidently Word (verified in Version 2106) is not using a standard XML parser to read the header part.

It wouldn't be much fun manipulating attribute order as part of the save process (ie after JAXB has marshalled), though potentially the canonicaliser could be modified to use the same order as Word (property: docx4j.jaxb.marshal.canonicalize)

**Comment by jhrtl** [comment]
Yes, significant attribute order in xml is quite ... unexpected. 
I found the current xml attribute order seems to be the one the java fields are written inside org.docx4j.vml.CTLine? Perhaps changing the order in there could help? Messing with the save process would be much harder, yes...

**Comment by plutext** [comment]
Well that was easy, thanks for the hint :-)
Tested with MOXy and the ReferenceImpl.  Should be good unless the canonicalizer is turned on...

**Comment by jhrtl** [comment]
Thanks for your help :)
