### ISSUE TITLE
Unable to extract TOC content from docx file

### ISSUE THREAD

**Issue by softkumsh** [plutext/docx4j#470]
Am trying to extract TOC and its content from the Docx file. But I am unable to get the TOC as well as TOC content.
My requirement is by providing the TOC, need to extract the relevant TOC contents.

WordprocessingMLPackage template = WordprocessingMLPackage.load(new FileInputStream(new File(name)));
MainDocumentPart documentPart = template.getMainDocumentPart();
Document wmlDocumentEl = documentPart.getJaxbElement();
Body body =  wmlDocumentEl.getBody();
TocFinder finder = new TocFinder();
new TraversalUtil(body.getContent(), finder);
SdtBlock currentSDT = finder.getTocSDT();

can you help me on this ?

**Comment by plutext** [comment]
Saw your post in the forum.  You'll need to attach your docx.

**Comment by softkumsh** [comment]
H
[CDE SAD Production 1.1.docx](https://github.com/plutext/docx4j/files/6944772/CDE.SAD.Production.1.1.docx)
Please find the attached file.
My use case needs to extract each of the content from the TOC level.

Advane thanks for your help.
