### ISSUE TITLE
The version 8.3.1 can not compatible with SpringBoot 2.3.6.RELEASE throwing NullPointerException

### ISSUE THREAD

**Issue by Accright** [plutext/docx4j#471]
When I use the version 8.3.1 in my project which is built by SpringBoot 2.3.6.RELEASE & spring-cloud Hoxton.SR8 ,the code can't run correctly. The code throws the NullPointerExption. I trace the code by IDEA breakpoint,founding that the class named NamespacePrefixMapperUtils getPrefixMapper() can not get PrefixMapper exactly because the code like this:
![image](https://user-images.githubusercontent.com/15204941/129016569-544b9cb1-eaec-429d-9d22-c9dbc5319090.png)
In fact,the true result of  "testContext.getClass().getName()" is "com.sun.xml.bind.v2.runtime.JAXBContextImpl" but not "  com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl" .this made the field "prefixMapper" can not be initialized correctly.When I use this filed in the other place,it throws the NullPointerExption.Anyone can help me resolve it? Thanks very much.

**Comment by plutext** [comment]
You need one and only one of:

- docx4j-JAXB-Internal (available for docx4j 8 only),
- docx4j-JAXB-MOXy (for docx4j 8 or 11),
- docx4j-JAXB-ReferenceImpl (for docx4j 8 or 11),

In your case, sounds like you'd want docx4j-JAXB-ReferenceImpl

See further https://www.docx4java.org/downloads.html

**Comment by Accright** [comment]
> You need one and only one of:
> 
> * docx4j-JAXB-Internal (available for docx4j 8 only),
> * docx4j-JAXB-MOXy (for docx4j 8 or 11),
> * docx4j-JAXB-ReferenceImpl (for docx4j 8 or 11),
> 
> In your case, sounds like you'd want docx4j-JAXB-ReferenceImpl
> 
> See further https://www.docx4java.org/downloads.html

Thanks for your reply.However,there is only the "docx4j-JAXB-Internal" & "docx4j-core" quoted in my pom.xml,like this:
`<dependency>
                <groupId>org.docx4j</groupId>
                <artifactId>docx4j-core</artifactId>
                <version>8.3.1</version>
            </dependency>
            <dependency>
                <groupId>org.docx4j</groupId>
                <artifactId>docx4j-JAXB-Internal</artifactId>
                <version>8.3.1</version>
            </dependency>`
Is there any issues?

**Comment by plutext** [comment]
What JVM are you running?

**Comment by Accright** [comment]
The information of the JVM is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0, as shown below. When I user the SpringBoot which version is "2.1.5" & SpringCloud version Greenwich.RELEASE, the code "NamespacePrefixMapperUtils getPrefixMapper() " behave normally.
![image](https://user-images.githubusercontent.com/15204941/129127714-ddd01f8e-171f-4dde-964a-67e9d7ebdf67.png)

**Comment by Accright** [comment]
Thanks a lot.I found that the pom that my project used quoted this : 
`<artifactId>jaxb-runtime</artifactId>
  <groupId>org.glassfish.jaxb</groupId>`
This pom made the error result.It worked when I remove this artifactId.
