### ISSUE TITLE
Wrong page breaking

### ISSUE THREAD

**Issue by tungndtt** [plutext/docx4j#472]
Hi,

Im writing a small application, which does the converting stuffs. By using the static function toPDF in class Docx4J, I can retrieve the whole content of a document in pdf-format. Everything works fine; however, the page breaking is not identical with the original document.

The below example shows the difference in the first page between the original version and the converted version:

![image](https://user-images.githubusercontent.com/57370037/129862017-ecf1367d-55b2-425e-929e-5a3f3dbd9b26.png)

Here is the code snippet
```
public static void Docx_Pdf(String docxPath, String outputPath) throws Exception {
	InputStream in = new FileInputStream(docxPath);
        WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load(in);

        FileOutputStream os = new FileOutputStream(outputPath);
        Docx4J.toPDF(wordMLPackage,os);
        os.flush();
        os.close();
}
```

**Comment by plutext** [comment]
That's to be expected using PDF via XSL FO and Apache FOP.  

As a long term project, we are looking at improving the fidelity.

In the meantime, for better fidelity options, please see https://www.docx4java.org/blog/2020/09/office-pptxxlsxdocx-to-pdf-to-in-docx4j-8-2-3/
