### ISSUE TITLE
Adding macro

### ISSUE THREAD

**Issue by tungndtt** [plutext/docx4j#475]
I want to generate a docm-file with macro. It was already posted [here](https://github.com/plutext/docx4j/blob/master/docx4j-samples-docx4j/src/main/java/org/docx4j/samples/MacroAdd.java) but in the class VbaDataPart, it doesn't seem to have any function called umshall. 

My project is in Maven and here are all docx4j dependencies in the project:
``
<dependency>
	<groupId>org.docx4j</groupId>
	<artifactId>docx4j</artifactId>
	<version>3.3.7</version>
</dependency>
``

``
<dependency>
	<groupId>org.docx4j</groupId>
	<artifactId>docx4j-ImportXHTML</artifactId>
	<version>3.3.6-1</version>
</dependency>
``

**Comment by plutext** [comment]
VbaDataPart extends JaxbXmlPart<JAXBElement<CTVbaSuppData>>
