### ISSUE TITLE
Corrupted docx file when passed through docx4j without modifying it when the original document contains statistical,hierarchy or combo charts

### ISSUE THREAD

**Issue by Dheeraj3reddy** [plutext/docx4j#481]
When I pass a word document containing a statistical chart(basically any chartEx) converting it to wordprocessingMLpackage and doing a getContents() of it. I am not doing any modifications to the wordprocessingMLpackage. The final document I am getting when I convert it back into a file is a corrupted document. I've checked the xml content and found that document.xml had some namespaces removed and some new ones added and this is the reason the document is corrupted. Can this issue be resolved? 
PFA original file and the corrupted file 
[chart1.docx](https://github.com/plutext/docx4j/files/7505811/chart1.docx)
[processed.docx](https://github.com/plutext/docx4j/files/7509704/processed.docx)

Method to reproduce - 

1. generate a inputstream from the file 
2. convert it to WordprocessingMLpackage
3. convert the mlpackage into outstream and save it into a new file 
This new file is being corrupted
docx4j-JAXB-ReferenceImpl version 11.2.9

**Comment by plutext** [comment]
Which version of docx4j are you using?

**Comment by Dheeraj3reddy** [comment]
docx4j-JAXB-ReferenceImpl version 11.2.9, I've also added the corrupted file for reference

**Comment by Dheeraj3reddy** [comment]
> Which version of docx4j are you using?

docx4j-JAXB-ReferenceImpl version 11.2.9, I've also added the corrupted file for reference

**Comment by plutext** [comment]
Just so you know, I'm planning to work on this later this week.

**Comment by Dheeraj3reddy** [comment]
Hi, any updates on this??

**Comment by plutext** [comment]
Now scheduled for tomorrow.

**Comment by plutext** [comment]
Update:  https://github.com/plutext/docx4j/commit/5e884239da932b4ef5df3b5d7b0597ad22432519 fixes the cx1-8 chart namespaces issue.

But there is still something strange about the output docx, and Word gives no clue about what that might be.

I also added https://github.com/plutext/docx4j/commit/db2c1147885481f1062c5538f85329dee0462f7c but the problem remains.

**Comment by Dheeraj3reddy** [comment]
> Update: [5e88423](https://github.com/plutext/docx4j/commit/5e884239da932b4ef5df3b5d7b0597ad22432519) fixes the cx1-8 chart namespaces issue.
> 
> But there is still something strange about the output docx, and Word gives no clue about what that might be.
> 
> I also added [db2c114](https://github.com/plutext/docx4j/commit/db2c1147885481f1062c5538f85329dee0462f7c) but the problem remains.

So comparing xml files also doesn't give any help?

**Comment by plutext** [comment]
Usually some difference in the XML is indeed the problem.  But here the difference is elusive.

**Comment by Dheeraj3reddy** [comment]
Hi, a small update from my side. I have tried the same on Waterfall chart. I have no idea why this is happening, but in the corrupted file's xml, in the file word/charts/chartEx1.xml, within the tag chartSpace -> chartData -> data -> numDim -> lvl when change **<cx:lvl formatCode="General" ptCount="8">** to **<cx:lvl ptCount="8" formatCode="General">** the file is not being corrupted anymore. Hope this could provide some help.

**Comment by plutext** [comment]
That's remarkable.  Well done!  

This is the second example of a case where attribute order matters to Word.  Sloppy programming at Microsoft...

https://github.com/plutext/docx4j/issues/469 explains how to control the attribute order.  

org.docx4j.com.microsoft.schemas.office.drawing.x2014.chartex.CTNumericLevel is what we need to change but those attributes already seem to be in the intended order!

Turns out we need a dedicated part for it, since DefaultXmlPart is handled via non-JAXB XML tech.

So we will have something like:

```
        /word/document.xml's rId4 is /word/charts/chartEx1.xml [org.docx4j.openpackaging.parts.WordprocessingML.ChartExSpacePart] http://schemas.microsoft.com/office/2014/relationships/chartEx containing:org.docx4j.com.microsoft.schemas.office.drawing.x2014.chartex.CTChartSpace

            /word/charts/chartEx1.xml's rId3 is /word/charts/colors1.xml [org.docx4j.openpackaging.parts.WordprocessingML.ChartColorStylePart] http://schemas.microsoft.com/office/2011/relationships/chartColorStyle containing:org.docx4j.com.microsoft.schemas.office.drawing.x2012.chartStyle.CTColorStyle

            /word/charts/chartEx1.xml's rId2 is /word/charts/style1.xml [org.docx4j.openpackaging.parts.WordprocessingML.ChartStylePart] http://schemas.microsoft.com/office/2011/relationships/chartStyle containing:org.docx4j.com.microsoft.schemas.office.drawing.x2012.chartStyle.CTChartStyle
```

**Comment by Dheeraj3reddy** [comment]
When can we expect this in a new release?

**Comment by plutext** [comment]
8.3.2 is in Maven now; a new 11.x release will follow, hopefully tomorrow.
