### ISSUE TITLE
Xmlrootelement not defined in chartEx/CTChartSpace

### ISSUE THREAD

**Issue by Dheeraj3reddy** [plutext/docx4j#488]
Xmlrootelement annotation is not present in org.docx4j.com.microsoft.schemas.office.drawing.x2014.chartex. This is creating trouble in marshalling. Do look into it

**Comment by plutext** [comment]
Please note this fix is in the jakarta.xml branch VERSION_11_4_0
but you can apply similar to v8.3.2 if you wish
