### ISSUE TITLE
log spamming of ArrayListWml.java in docx4j-openxml-objects project

### ISSUE THREAD

**Issue by imtiazShakil** [plutext/docx4j#489]
After [this commit](https://github.com/plutext/docx4j/commit/63e327057b2aac1e7f82535bb03f9ff8c31daf0f) if `removeAll` method is called it logs a text with warning text `"This method won't remove an object if it is wrapped in a JAXBElement"`. 

I understand that you want to notify the user that this method call won't remove wrapped `JAXBElement` but this caused huge redundant warnings on our server. A lot of classes like `org.docx4j.wml.P` , `org.docx4j.wml.Tc` returns `ArrayListWml` when `getContent()` method is called, thus any time we call like this 

```java
para.getContent().removeAll(runList);
``` 
Or     
```java
tc.getContent().removeAll(paraList);
```
this warning spams our logs so much so that it becomes difficult to find and see other important logs.

Can you fix this somehow?

**Comment by plutext** [comment]
https://github.com/plutext/docx4j/commit/335103fd454c9b38e2fbf1f75fab6a08707ec4ff changes it from warn to info level.

But in the meantime you could adjust your logging config so that class only logs at error level.
