### ISSUE TITLE
Parse error while unmarshalling chartEx charts

### ISSUE THREAD

**Issue by Dheeraj3reddy** [plutext/docx4j#490]
While unmarshalling the xml files of chartEx charts such as Statistical Chart 2 and Waterfall Chart 1, I am encountering a `SaxParseException2` which is being caused by `NumberFormatException`. I tried to find the cause and one is I possibly think is causing this is the wrong structure of tags. While the parser is expecting something of this sort 
`<cx:axisId>2</cx:axisId>`, the xml file for chart contains `<cx:axisId val="2"/>`. I don't know if this is error from the unmarshaller side or while creating the xml element itself, but please do look into it.
**Method to reproduce**

- Create a docx file with either Statistical Chart 2 or Waterfal Chart 1. 
- Try to unmarshal the xml file corresponding to the respective chart

**Comment by plutext** [comment]
I need to regenerate the JAXB classes from https://docs.microsoft.com/en-us/openspecs/office_standards/ms-odrawxml/e2723b0a-9120-42a5-bd11-c252ccb13c1e since that new revision contains changes such as:

```   <xsd:complexType name="CT_Subtotals">
     <xsd:sequence>
       <xsd:element name="idx" type="xsd:unsignedInt" minOccurs="0" maxOccurs="unbounded"/>
     </xsd:sequence>
   </xsd:complexType>
```

becomes

```
   <xsd:complexType name="CT_SubtotalIndex">
     <xsd:attribute name="val" type="xsd:unsignedInt" use="required"/>
   </xsd:complexType>
   <xsd:complexType name="CT_Subtotals">
     <xsd:sequence>
       <xsd:element name="idx" type="CT_SubtotalIndex" minOccurs="0" maxOccurs="unbounded"/>
     </xsd:sequence>
   </xsd:complexType>
```

**Comment by plutext** [comment]
This is now fixed in https://github.com/plutext/docx4j/tree/VERSION_11_4_0
Not in Maven yet; are you happy building this branch yourself?
