### ISSUE TITLE
OSGi information misses on mvncentral jar

### ISSUE THREAD

**Issue by Nutstree** [plutext/docx4j#494]
The mvn configuration has a maven-bundle-plugin configuration, so I would expect Manifest information in the jar. However, the jar deployed on mvncentral does not contain Manifest information.

**Comment by plutext** [comment]
You are right; docx4j-core-8.3.2 MANIFEST.MF says:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: jharrop
Build-Jdk: 1.8.0_292
```

11.3.2 is similar:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: jharrop
Build-Jdk: 14.0.1
```

Looks like the release plugin steps would need to be customized to  [add the manifest goal](https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#_adding_osgi_metadata_to_existing_projects_without_changing_the_packaging_type) during `release:prepare` or `release:perform`: https://stackoverflow.com/a/15185774/1031689  

Happy to accept a suitable PR.

We haven't done a whole lot with OSGi, but there is https://github.com/plutext/docx4j/blob/master/OSGi.md

**Comment by plutext** [comment]
Present in 11.4.5
