### ISSUE TITLE
Encoding bug in MainDocumentPartFilterOutputStream#write(...)

### ISSUE THREAD

**Issue by thoraage** [plutext/docx4j#503]
### Preconditions:
* File encoding set to anything but UTF-8
* Document with special characters early in the body

### Explanation

Document is split at the body-mark in order to add a version comment. This is done by creating a string (line 40) from the byte-array and searching for "body" in that. If no "body" is found the byte-array is written as-is. If it is found then the string is written up to body-mark, then comment is written and then string after body-mark.

Problem here is that the string is created (line 40) with local file encoding and then printed as UTF-8 (see lines 49 and 54).

I believe the best solution here should be to create the string in line 40 as UTF-8.

### Circumvention of problem

Turning of version comment by declaring "docx4j.jaxb.marshal.suppressVersionComment" to "true" in _docx4j.properties_ will bypass the problem entirely.

**Comment by plutext** [comment]
Thanks for this, please check the commit.

**Comment by plutext** [comment]
Fixed/released in docx4j 11.4.6
