### ISSUE TITLE
“Word found unreadable content” when header contains a shape and an image is inserted for a rich text control

### ISSUE THREAD

**Issue by devopsix** [plutext/docx4j#504]
The template DOCX file contains:

- A shape (a line in this particular) in the header section
- A rich text content control in the main document part

![image](https://user-images.githubusercontent.com/58369032/162169773-1ada42ff-b1d3-499f-ac01-7a33ede5dfa3.png)

The rich text content control is to be replaced by a paragraph with an image: `<p><img src="..."></img></p>` (contained in the XML in escaped form).

After binding the content control with docx4j, when opening the resulting document in Word a “Word found unreadable content” error message is shown.

![image](https://user-images.githubusercontent.com/58369032/162168515-7adb0877-e288-4e68-948c-3f62e89fad8d.png)

The issue goes away as soon as the shape is removed from the template's header section before doing the binding.

Attached is a working sample for reproducing the issue. Extract [docx4j-xhtml-image.zip](https://github.com/plutext/docx4j/files/8441632/docx4j-xhtml-image.zip), check out `Docx4jXhtmlImageTest.java`, run `mvn test` and open out.docx in MS Word.

**Comment by plutext** [comment]
Thank you for the clear and reproducible issue.

This turns out to be https://github.com/plutext/docx4j-ImportXHTML/issues/71 which I will look at expediting

**Comment by plutext** [comment]
Fixed/released in docx4j-ImportXHTML 11.4.6 with docx4j 11.4.6
