### ISSUE TITLE
Usage of AGPL in FontSubstitutions.xsd

### ISSUE THREAD

**Issue by onewaypub** [plutext/docx4j#506]
Hello,

we are in the process of creating our own open source project. In this project we are using your library and have found out during code scans that you have placed a file under the AGPL-3.0.only license. To be exact the file 

docx4j-core/org/docx4j/fonts/substitutions/FontSubstitutions.xsd

The whole project is licensed under Apache 2.0, but we have learned that Apache 2.0 is incompatible with AGPL-3.0-only, which to our knowledge would put the whole project under AGPL-3.0-only (due to the strict copy left).

So our question would be if you could put the license in the file under Apache 2.0 as well.

Many greetings
Onewaypub

**Comment by plutext** [comment]
Oops, now fixed at https://github.com/plutext/docx4j/commit/8fc2ce124cc6f8e027b1486493b418843174490e
Should've been changed more than a decade ago!
