### ISSUE TITLE
docx4j overrides JDK11 implementation of JAXP javax.xml.transform.TransformerFactory leading to problems

### ISSUE THREAD

**Issue by omasseau** [plutext/docx4j#538]
Since I included docx4j 11.3.2 in my project I get these type of errors : 
_java.lang.IllegalArgumentException: http://javax.xml.XMLConstants/property/accessExternalDTD attribute value not recognized_ 

This is the case if I call for example : 
`transformerFactory.getAttribute(XMLConstants.ACCESS_EXTERNAL_DTD)`

I noticed that the implementation of TransformerFactory thas was loaded was : 
_org.docx4j.org.apache.xalan.processor.TransformerFactoryImpl_

which does not support the _http://javax.xml.XMLConstants/property/accessExternalDTD_ attribute while the default implementation provided by the JDK 11 (_com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl_) supports it perfectly fine.

Do you really need to have your own (outdated) implementation of TransformerFactory when the JDK already provides it ?

At least when you add an explicit dependency on Xalan, we were able to exlude the dependency in the pom.xml to avoid this problem.

**Comment by plutext** [comment]
> Do you really need to have your own (outdated) implementation of TransformerFactory when the JDK already provides it ?

xsltc doesn't support Xalan extension functions, so without interpretive Xalan, you'd experience loss of functionality where this is used eg export to HTML, XSL FO; content control bind processing.  For some of this we have alternative implementations which don't use XSLT, but not to parity.

What does System.getProperty("javax.xml.transform.TransformerFactory") return? (On Java 17 it returns null).

Before using docx4j, try
			System.setProperty("javax.xml.transform.TransformerFactory",
					"com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");

Doing this should allow docx4j to use its preferred implementation internally, without affecting the rest of your application.

**Comment by plutext** [comment]
See https://docs.oracle.com/javase/7/docs/api/javax/xml/transform/TransformerFactory.html#newInstance() for the ordered lookup procedure and trouble-shooting tips.
