### ISSUE TITLE
Add support for Repeating Section Content Control in Word 2013

### ISSUE THREAD

**Issue by cknaap** [plutext/docx4j#54]
Word 2013 introduces the Repeating Section Content Control. It would be very useful if Docx4j would evaluate and populate this control with the repeating data from the custom XML that is bound to it. I think this could be used instead of the OpenDoPE implementation of repeating data.

Please refer to [RepeatingSectionContentControl.zip](http://sdrv.ms/10KXFJ7) for an example document. It includes:
- Order_ContentControls.docx: a very simple order report containing a single order number and the aforementioned Repeating Section Content Control for the OrderLine items.
- OrderExample1.xml: the xml data that was loaded into the Word document.
- Order.xsd: the schema for the xml data.

See the [question on StackOverflow](http://stackoverflow.com/questions/15874666/does-docx4j-support-the-new-word-2013-repeating-section-content-control) that resulted in this issue.

**Comment by plutext** [comment]
Suppored since ~ 3.2.2: https://www.docx4java.org/blog/2015/01/word-2013-repeatingsection-content-controls-ready-for-prime-time/
