### ISSUE TITLE
the created word file  toc can't jump

### ISSUE THREAD

**Issue by yong-zeng** [plutext/docx4j#553]
<dependency>
      <groupId>org.docx4j</groupId>
      <artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
      <version>8.3.9</version>
    </dependency>

`
WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage
				.load(new File(
						"template.docx"));

		MainDocumentPart documentPart = wordMLPackage.getMainDocumentPart();

		VariablePrepare.prepare(wordMLPackage);

documentPart.variableReplace(variables);

		ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

		wordMLPackage.save(outputStream);
`

**Comment by plutext** [comment]
Do you mean your TOC doesn't have working hyperlinks?

**Comment by yong-zeng** [comment]
yes ,I solved this problem by remove the code 'VariablePrepare.prepare(wordMLPackage);'
