### ISSUE TITLE
 Transitive vulnerable dependency maven:commons-codec:commons-codec:1.12

### ISSUE THREAD

**Issue by alexmaryin** [plutext/docx4j#554]
Intellij Idea shows the following warning in Gradle files using docx4j ver. 11.4.9 dependency:

Provides transitive vulnerable dependency maven:commons-codec:commons-codec:1.12
[Cxeb68d52e-5509 3.7 Exposure of Sensitive Information to an Unauthorized Actor vulnerability pending CVSS allocation](https://devhub.checkmarx.com/cve-details/Cxeb68d52e-5509/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea)

Apache has updated mentioned library commons-codec:commons-codec to version 1.16.0.
Please update that transitive dependency in docx4j to avoid warning.

**Comment by plutext** [comment]
Fixed at https://github.com/plutext/docx4j/commit/a2184cab4c8abd9714ff0e9867d4965dfc239ff8
