### ISSUE TITLE
The generated class names are all numbers.

### ISSUE THREAD

**Issue by xfy520** [plutext/docx4j#555]
![image](https://github.com/plutext/docx4j/assets/78788091/22c6cfaa-edad-4920-a024-3199744f4fbc)

How to customize and add a class name prefix?thank you!

**Comment by plutext** [comment]
I guess you have paragraph styles in your docx with a numeric w:styleId?  Please unzip your docx and attach a copy of word/syles.xml

**Comment by xfy520** [comment]
[test.zip](https://github.com/plutext/docx4j/files/12388200/test.zip)

This is to parse the word file，thank you!

**Comment by plutext** [comment]
Your styles part contains style definitions:

- <w:style w:type="paragraph" w:default="1" w:styleId="1"><w:name w:val="Normal"/>
- <w:style w:type="character" w:default="1" w:styleId="4"><w:name w:val="Default Paragraph Font"/>
- <w:style w:type="table" w:default="1" w:styleId="2">

Typically those styleId values would not be numbers, but strings similar to w:name/@w:val (eg 'normal').

This is where the numbers are coming from.

Workaround:  create your docx with non-numeric @w:styleId.
