### ISSUE TITLE
handling broken node docx library output

### ISSUE THREAD

**Issue by 786Dheeraj** [plutext/docx4j#556]
Hi,
We are using a node library to generate our word documents - [docx](https://www.npmjs.com/package/docx?activeTab=readme). The documents generated through this library are not being parsed correctly when I call `documentPart.getMainDocumentPart().getContent();`. We are getting an empty document once we do this. We went through logs and found that there is a `NumberFormatException` being thrown which was due to the fact the **page Margin** tag is as such
`<w:pgMar w:top="1in" w:right="1in" w:bottom="1in" w:left="1in" w:header="708" w:footer="708" w:gutter="0"/>` the dimensions are mentioned in **inches** instead of **twips**. This is throwing the numberformat exception, and causing the document to be replaced by new empty document. 

Can you please look into this issue.

**Comment by plutext** [comment]
You should raise at issue with the node library project, asking them to fix the unit of measurement used in those attributes.

In the meantime, it is possible to workaround an issue such as this by copying org/docx4j/jaxb/mc-preprocessor.xslt and adding a new rule.  Then set property docx4j.jaxb.JaxbValidationEventHandler to point to your xslt file.

https://github.com/plutext/docx4j/blob/VERSION_11_4_8/docx4j-core/src/main/resources/org/docx4j/jaxb/mc-preprocessor.xslt is the preprocessor.xslt docx4j ships with.

**Comment by 786Dheeraj** [comment]
Hi @plutext  , thanks a lot for the reply. Just wanted to know one thing, I've found a link for specifications of [same](https://learn.microsoft.com/en-us/previous-versions/office/developer/office-2003/aa214311(v=office.11)). Am I following the right link? Also I've tried some other libraries by converting the docx to pdf, and some more operations and they seem to be working fine. Just wanted to make sure that the only dimensions allowed are in twips.

**Comment by plutext** [comment]
That's the old Word 2003 spec (though the definition is essentially the same).

You want Ecma Office Open XML.  Section 17.6.11;  alternatively see http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/pgMar.html

It says

```The possible values for this attribute are defined by the [ST_SignedTwipsMeasure](http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/ST_SignedTwipsMeasure.html) simple [type](http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/type.html) (§2.18.88).```

That link says

```
ST_SignedTwipsMeasure (Signed Measurement in Twentieths of a Point)

This simple type specifies that its contents will contain a positive or negative whole number, whose contents consist of a measurement in twentieths of a point (equivalent to 1/1440th of an inch).
```
