### ISSUE TITLE
Add part for .wdp JPEG XR

### ISSUE THREAD

**Issue by plutext** [plutext/docx4j#560]
ERROR org.docx4j.openpackaging.contenttype.ContentTypeManager - No subclass found for /word/media/hdphoto1.wdp; defaulting to binary

**Comment by plutext** [comment]
See further https://stackoverflow.com/questions/77216858/docx4j-error-no-subclass-found-for-word-media-hdphoto1-wdp-defaulting-to-bin/77217506#77217506

**Comment by plutext** [comment]
In Word (version 2402), the insert picture dialog supports emf, wml, jpg|jpeg, jfif, jpe, png, bmp, dib, rle, gif, emz, wmz, tif|tiff, svg, ico, webp.

 if you add an image of type JPEG XR (jxr), Word converts it to png.

So you should convert your .jxr/.wdp image to png somehow, then add that.

I haven't experimented to see what Word does with a docx which has been made to contain a .jxr image.

It seems like the jxr format gained so little traction that Microsoft didn't bother to add it to Word.

**Comment by matthiaso** [comment]
We are experiencing the same log message - even though we do not know how this image was added to the Word file.

**Comment by plutext** [comment]
webp support (in 17.0.1):  https://github.com/plutext/docx4j/commit/b552ecd67560151ee965cefc34f3ef89574142a6

.jxr support outstanding

**Comment by plutext** [comment]
Office 2010, 2013 and later (Word and Powerpoint) can insert a JXR file,  but they all convert it to PNG on the fly.
None of them appear to support displaying the JXR in a Word document, whether legacy VML or the modern format.
Tried image/jxr, image/vnd.ms-photo but not image/hdp.

**Comment by work-lto** [comment]
We experience the same log message.

I was able to insert a .wdp image into a Word File (choose all files in the file explorer) - see attachment 

It was not converted into png judging from the contents of /word/media folder

[wdp-example.docx](https://github.com/user-attachments/files/30750793/wdp-example.docx)
