### ISSUE TITLE
ignore namespace w16du not in namespaces list

### ISSUE THREAD

**Issue by jackFromBdx** [plutext/docx4j#573]
Hi,
I have some docx I can't open with word ("unreadable content")
In the document.xml, there is "mc:Ignorable="w14 w15 w16se w16cid w16 w16cex w16sdtdh w16du wp14" but there is not namespace w16du in the namespaces list.
If I remove the w16du ref, the docx opens.
Have you already meet the issue ?

**Comment by plutext** [comment]
Fixed at https://github.com/plutext/docx4j/commit/c94f61427c193afa7af0cde89df2bfd8947d38be
Due for release next week

**Comment by jackFromBdx** [comment]
thank you

**Comment by jackFromBdx** [comment]
will there be a version in 8.X ?
