### ISSUE TITLE
Add html type content inside content control

### ISSUE THREAD

**Issue by src107** [plutext/docx4j#575]
I have a word document with a body level content control and inside that a child content control, I want to insert some HTML content inside the child content control and replace it content with the html content. Is it possible? Can someone please help
XML structure
<img width="1028" alt="image" src="https://github.com/plutext/docx4j/assets/49275977/9dd701fb-2808-4167-8448-316256eaa58f">
@plutext

**Comment by plutext** [comment]
OpenDoPE databinding can do this;  w:sdtPr/w:tag needs to contain od:ContentType=application/xhtml+xml'

```
  		<xsl:when test="contains( string(w:sdtPr/w:tag/@w:val), 'od:ContentType=application/xhtml+xml' )">
  			<!--  Convert XHTML.
  			
  				  For all except the run-level case, we need to be able to have block level content.
  				  Which means we need to be inserting into a rich text control,
  				  which in turn means there can't be a w:sdtPr/w:dataBinding. 
```

Use the Word Add-In to set up your docx appropriately.
