### ISSUE TITLE
About word documents with Sensitivity

### ISSUE THREAD

**Issue by EphemearlDusk** [plutext/docx4j#583]
When I add Sensitivity to the document, the generated document cannot be displayed normally
![Screenshot 2024-06-27 151044](https://github.com/plutext/docx4j/assets/59352805/d0266256-850e-4d0e-84a2-5e05d8a2f285)
![Screenshot 2024-06-27 151221](https://github.com/plutext/docx4j/assets/59352805/b565f440-d997-4021-a77e-58747bb9e0c1)

**Comment by plutext** [comment]
Could you please attach a sample docx with sensitivity applied?

**Comment by EphemearlDusk** [comment]
okay.
[test.docx](https://github.com/user-attachments/files/16009992/test.docx)
[outputFile.docx](https://github.com/user-attachments/files/16009994/outputFile.docx)

**Comment by plutext** [comment]
mc:Ignorable contains w16du, but namespace  xmlns:w16du="http://schemas.microsoft.com/office/word/2023/wordml/word16du" is missing from output document.xml

 11.4.10 and 8.3.10 fix this: https://www.docx4java.org/forums/docx-java-f6/new-namespace-mapping-issue-t3112.html
