### ISSUE TITLE
POI writes w:val="off", but BooleanDefaultTrue.isVal got true

### ISSUE THREAD

**Issue by will86** [plutext/docx4j#585]
I am using docx4j V8.3.11
while I having the following xml

`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" >
  <w:body>
    <w:p>
      <w:r>
        <w:rPr>
          <w:rFonts w:ascii="Arial" w:eastAsia="Arial" w:hAnsi="Arial"/>
          <w:sz w:val="18"/>
          <w:szCs w:val="18"/>
          <w:b w:val="on"/>
          <w:i w:val="off"/>
          <w:strike w:val="off"/>
          <w:color w:val="000000"/>
        </w:rPr>
        <w:t>SIMPLE</w:t>
    </w:r>
    </w:p>
  </w:body>
</w:document>`

Simply, I tried to unmarshal the above xml to an object

`
 String xml = "↑↑↑";
 Object o = XmlUtils.unmarshalString(xml);
 System.out.println(o);`

In the o document, the attribute I  and strike was not null, and the method of isVal() within BooleanDefaultTrue returned true.

I don't think its right, So I want some help here.

![SCR-20240731-ngeq](https://github.com/user-attachments/assets/bc81dfd5-ea05-46e8-aab2-d784b26a338b)

**Comment by will86** [comment]
@plutext Sorry to disturb you.
 I've been bothering me about this issues for a while, and I want you to take a look at how to solve it.
Thanks a lot.

**Comment by plutext** [comment]
By way of background:

```
	<xsd:complexType name="BooleanDefaultTrue">
		<!--
		
		Replaces CT_OnOff, for more intuitive field generation by JAXB.
		
		http://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#boolean
		says ·boolean· can have the following legal literals {true, false, 1, 0}.
		
		Don't use this for elements where Word 2007 passes 'on' or 'off' (which type="xsd:boolean" default="true" allows).
		
		Note that a third party processor could choose to use 'on' or 'off', even where
		Word doesn't.  This would cause trouble.
		
		Hopefully the result of standardisation will be to formally get rid
		of 'on' and 'off', and use xsd:boolean instead.   
		
		-->
		<xsd:attribute name="val" type="xsd:boolean" default="true">
			<xsd:annotation>
				<xsd:documentation>True/False Value (default is
					true)</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
```

so values 'on', 'off' aren't supported.

Where did your input xml come from?

For text which is struck out, Word and docx4j typically produce  <w:strike/>.

<w:strike w:val="off"/> is redundant, but <w:strike w:val="false"/> should work.

**Comment by will86** [comment]
@plutext  Thank you for getting back to me.

There is another system that using POI(v5.2.2).
The system are calling the API: `XWPFRun#setStrikeThrough(false);`, and generates some docx file.

Unzip these docx files, within document.xml, I got this attribute.
`<w:strike w:val="off"/>`

I tried to open the docx file with MSOffice(2019)、 Office365,
and these apps didn't hava the strikethrough render.

**Comment by plutext** [comment]
Similar to https://github.com/plutext/docx4j/issues/586#issuecomment-2280206997 you could pre-process the input to convert w:val=on|off to true|false.  That would be enough, though you could also completely remove `<w:strike w:val="off"/>`

For the general case, I'd suggest you use:

```
docx4j.jaxb.preprocess.always=MainDocumentPart,HeaderPart,FooterPart,EndnotesPart,FootnotesPart
```

To do this, configure your mc-preprocessor; see https://github.com/plutext/docx4j/blob/VERSION_11_4_12/docx4j-samples-resources/src/main/resources/custom-preprocessor.xslt

Add something like:

```
<!-- POI writes 'on' and 'off', no good for docx4j -->  
<xsl:template match="@w:val" >
  	<xsl:choose>
  		<xsl:when test=".='true' or .='on' or .='1'">
		  	<xsl:attribute name="w:val">true</xsl:attribute>
  		</xsl:when>
  		<xsl:otherwise>
		  	<xsl:attribute name="w:val">false</xsl:attribute>
  		</xsl:otherwise>
  	</xsl:choose>
  </xsl:template>  
```

(This is untested, so please confirm it works)

To use this custom preprocessor, you need to uncomment the following line in your docx4j.properties file on your classpath:
	
	 #docx4j.jaxb.JaxbValidationEventHandler=custom-preprocessor.xslt
	 
If you don't have a  docx4j.properties file, you can find a sample at
	https://github.com/plutext/docx4j/blob/master/docx4j-samples-resources/src/main/resources/docx4j.properties

**Comment by will86** [comment]
@plutext 

Thanks~

It works for me, but I modified the `custom-preprocessor.xslt` config as following:

>     
    <xsl:template match="w:strike">
        <xsl:choose>
            <xsl:when test="@w:val='false' or @w:val='off' or @w:val='0'">
                <w:strike w:val="false"/>
            </xsl:when>
            <xsl:otherwise>
                <w:strike w:val="true"/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>



Similarly, I also add the same config for `w:b` and `w:i` to avoid POI off value.
