### ISSUE TITLE
Docx4j Word Addin Plugin Download Link not working

### ISSUE THREAD

**Issue by onkar-indellient** [plutext/docx4j#587]
The following links are no longer working: 

1. https://www.plutext.com/dn/downloads/1472868282152/Docx4j_Helper_3-3-1-03.exe?_ga=2.114750279.1178368136.1722527572-1540217022.1722527572
3. http://www.plutext.com/dn/downloads/1472868282152/Docx4j_Helper_3-3-1-03.exe?_ga=2.224088786.837929860.1604649493-60107745.1601964072
5. https://www.docx4java.org/docx4j/Docx4j_Helper_8-2-1-1.exe

Can someone please share a working link?

**Comment by plutext** [comment]
Per https://www.docx4java.org/forums/announces/docx4j-helper-addin-2023-t3108.html please use https://www.docx4java.org/docx4j/Docx4j_Helper_8-2-1-2.exe

**Comment by onkar-indellient** [comment]
Thank You, I was able to download it :)
