### ISSUE TITLE
Chinese font issue

### ISSUE THREAD

**Issue by Adityadeopurkar** [plutext/docx4j#589]
Hi All,

My application is using mergeDocx for merging word documents which have various languages.
The merge function is taking too long (more than 5 mins compared to 10-20 secs normally) for any set of documents which has Chinese language, the error messages that I see are as follows,
PropertyResolver(getFontnameFromStyle) - couldn't find basedOn:DocDefaults
PropertyResolver(getDefaultFontEastAsia) - Don't know how to handle: MINOR_H_ANSI
Is there a way to handle this ?

**Comment by plutext** [comment]
For help with our commercial MergeDocx component, please email support@plutext.com

Typically we'll need to see sample input documents.

What is your log configuration?

**Comment by Adityadeopurkar** [comment]
Let me take this on mail then through official channel.
thanks
